### ISSUE TITLE
Add `--json` option to call and invoke commands

### ISSUE THREAD

**Issue by Arcticae** [software-mansion/protostar#1057]
As a StarkNet smart contract developer, I want outputs of `call` and `invoke` to be available in "raw" (preferably JSON) format so that i can use protostar in simple CI/bash scripting cases.
That should be allowed through a `--json` option, and the outputs should have our own internal schema (for invoke responses), so that it remains fairly consistent and clear throughout the products' lifetime (this excludes response body of `call` which can vary depending on the called function).

**Comment by mkaput** [comment]
duplicate of #1114
