### ISSUE TITLE
Refactor `gateway_facade`

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#1096]
https://github.com/software-mansion/protostar/pull/1055#discussion_r1013173155
Distinguish signed and unsigned transactions.

Also, I think it's worth separating sending and waiting for the transaction from creating the transaction as proposed here:
https://github.com/software-mansion/protostar/pull/1059#pullrequestreview-1151056455 

Creating and validating the transaction is [orthogonal](https://flylib.com/books/en/1.315.1.23/1/) to sending the transaction.

**Comment by mkaput** [comment]
I don't understand the rationale behind separating sending and waiting. Aren't these just `Future`s but implemented in more cumbersome way?

**Comment by mkaput** [comment]
On the other hand, I think it would be nice if we could reduce complexity of `GatewayFacade` by using other measures of extending regular `GatewayClient` with stuff we want and sticking with Starknet.py's APIs

**Comment by kasperski95** [comment]
`GatewayFacade` repeats the logic that sends and waits for acceptance in the meantime for various transactions.
