### ISSUE TITLE
Docs issue: wrong numbers in example

### ISSUE THREAD

**Issue by Pet3ris** [software-mansion/protostar#1125]
Hi There,

Awesome framework and documentation, been fun to use it!

Seems like this example (https://docs.swmansion.com/protostar/docs/tutorials/testing/cheatcodes/example) has a small issue:

![image](https://user-images.githubusercontent.com/224585/200539357-bec204ed-a778-4bf9-88f7-fc815483a384.png)

Should this:

```
# (3,4)
```

Be

```
# (5,6)
```

**Comment by mkaput** [comment]
Hey! Good catch! Thanks for reporting. We will push a fix soon.
