### ISSUE TITLE
Support cairo-rs

### ISSUE THREAD

**Issue by karol-bisztyga** [software-mansion/protostar#1158]
The goal is to run cairo programs on the cairo-rs (cairo VM written in rust) from the protostar.

Useful links:
https://github.com/lambdaclass/cairo-rs
https://github.com/lambdaclass/cairo-rs-py

**Comment by karol-bisztyga** [comment]
https://github.com/lambdaclass/cairo-rs/issues/620

**Comment by MaksymilianDemitraszek** [comment]
Closing in favour of #1844
