### ISSUE TITLE
Rework waiting procedure in `declare` and `deploy` commands

### ISSUE THREAD

**Issue by mkaput** [software-mansion/protostar#1162]
Replace `--wait-for-acceptance` command with interactive, CTRL-C based process, like Expo does:

![image](https://user-images.githubusercontent.com/3450050/202149741-6690d8cc-5238-47e7-a804-830294f996b1.png)

Think through, how to handle this for JSON. Possibly, introduce inverse CLI flag (`--no-wait-for-acceptance`).

Also, add `protostar await` command which accepts transaction hash and waits for its acceptance.

**Comment by MaksymilianDemitraszek** [comment]
I assume that `ctrl + c` does not stop the build here, but I am worried it might suggest it user that it does
