### ISSUE TITLE
Add a section in documentation for `json` outputs of commands

### ISSUE THREAD

**Issue by Arcticae** [software-mansion/protostar#1210]
In order to fill the void created by coming removal of migrations, we should probably hint the users to use the new flow since we're heading towards json commands output (and we'll be adding some interesting features to it in the future).

**Comment by mkaput** [comment]
My general line of thought here was:
1. `--json` flag is well documented in CLI reference
2. In migrations page we have a box that recommends using CLI.
3. Perhaps we should add a tutorial describing how to write a script in bash ?

**Comment by MaksymilianDemitraszek** [comment]
Deployments scripting section
