### ISSUE TITLE
Provide a way to bypass ABI contract fetching from API

### ISSUE THREAD

**Issue by Arcticae** [software-mansion/protostar#1216]
Generally speaking ABI doesn't have to be compliant with the bytecode present on the blockchain.
We should provide a way for user to pass the contracts' ABI to the commands in such situations. 

This is not high priority, but a nice-to-have.

**Comment by MaksymilianDemitraszek** [comment]
Is this one closed @kasperski95 ?

**Comment by kasperski95** [comment]
No. Right now, only `call` command supports custom ABI.
