### ISSUE TITLE
Fix handling calldata provided to `protostar invoke`

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#1220]
> I have to provide 2 inputs, a uint256 and a struct array (struct is (felt, felt)), so something like that: —inputs uint256 array_len array_values. With an array of length 1, it is supposed to look like that: —inputs int int int int. The problem is that it keeps returning me that error `Provided 4 positional arguments, 2 possible..`

**Comment by Radinyn** [comment]
Turns out the user was providing invalid input

**Comment by kasperski95** [comment]
Reopening. Too many reports.

https://discord.com/channels/793094838509764618/964116575387021413/1050181056344629318

**Comment by Darlington02** [comment]
Hey @kasperski95, seems this issue still persists with the recent upgrade to v0.9.0? can't invoke the UDC command directly, still tells me
```04:14:37 [ERROR] Input validation failed with the following error:                                                                                                                           
Provided 5 positional arguments, 4 possible.

**Comment by kasperski95** [comment]
Yes, it's not fixed in the v0.9.0.

Did you try using `protostar deploy` instead? In Protostar v0.9 it should send the invoke transaction to the UDC.

**Comment by Darlington02** [comment]
Yes the `protostar deploy` command works.

But I have issues when deploying upgradeable contracts which requires a calldata array...what way would you suggest I go about it?

**Comment by kasperski95** [comment]
> But I have issues when deploying upgradeable contracts which requires a calldata array...what way would you suggest I go about it?

Did you precede array data with array length, e.g. `[3, 1,1,1]`? Can you create a new issue with a reproducible example?

**Comment by 0xKarasu** [comment]
Hey @kasperski95, is it possible that the CLI doesnt recognize a struct when we pass one 

I'm trying to do invoke a function which signature is: `colorizePixels(pxlId: Uint256, pixel_colorizations_len: felt, pixel_colorizations: PixelColorization*)`
`PixelColorization` is a 2 felt-members struct.

I'm supposed to pass `2 (Uint256) + 1 (size) + 2 (struct) * size = 5` inputs. 

My command is:
`protostar --profile testnet2 invoke --contract-address 0x020........ae7eb2 --function colorizePixels --inputs 1 0 1 24 29 --account-address 0x0443......cf2 --private-key-path ./.env --max-fee 100000000000000 --json `

It still tells me:
`Provided 5 positional arguments, 2 possible.`

Here is an example transaction performed with starkscan :
`https://testnet-2.starkscan.co/tx/0x64f64267c90d573b8d997b3db6c9984db4bb839e7f5dd05118863802a7459f0`
