### ISSUE TITLE
Invalid gas estimation

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#1245]
I have just tried this feature on some tests, the results don't seem to represent the true costs.
Here is an example of some test results:

Run1: 
```
time=17.32s, gas=4059, steps=147619, memory_holes=32442 pedersen_builtin=21 range_check_builtin=7495
```
Run2:
```
time=31.45s, gas=4059, steps=389198, memory_holes=30887 pedersen_builtin=21 range_check_builtin=6970
```

Resources on run2 are considerably higher (especially steps) but the gas result is the same

_Originally posted by @amanusk in https://github.com/software-mansion/protostar/issues/1195#issuecomment-1340683586_

**Comment by amanusk** [comment]
Tested this codebase

https://github.com/HerodotusDev/herodotus-eth-starknet/tree/v2

This is the command (latest protostar build)
```
 /home/amanusk/Code/Cairo/protostar/dist/protostar/protostar test --estimate-gas ./tests/contracts/test_l1_facts_registry.cairo::test_prove_account
```
