### ISSUE TITLE
`GLIBC_2.35 not found` on Debian

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#1293]
> $ protostar init
> [459] Error loading Python lib '~/.protostar/dist/protostar/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6:
version `GLIBC_2.35` not found (required by ~/.protostar/dist/protostar/libpython3.9.so.1.0)

**Comment by Psyclonic** [comment]
@kasperski95 Any progress on this? I'm getting the same error.
