### ISSUE TITLE
Print TX hash in hex

### ISSUE THREAD

**Issue by milancermak** [software-mansion/protostar#1324]
When using `deploy`, the transaction hash is printed in decimal instead of hex. Here's an example:

```sh
PROTOSTAR_ACCOUNT_PRIVATE_KEY=0xee662dfc3ad7dc7e2e74924d50ee2d22 protostar -p devnet deploy 0x05277a800869ca74b42495ba57823673905360270c013421355774f6622d1c1d --account-address 0x648a214febc8695f367e95dfd58edd86fbd23d67bafa611957821b24e395c99 --max-fee 10000000000000000 --chain-id 1536727068981429685321

Invoke transaction was sent to the Universal Deployer Contract.
Contract address: 0x037c626a70b22216d11315396e77f3483760b5325f0a37addf4ea55fa9446507
Transaction hash: 1309246811559898348185976446575323624596292679113464176759093332565829975680
17:46:42 [INFO] Execution time: 1.60 s
```

Hex is preferred as it can be used in other tools (e.g. the starknet CLI, which doesn't play well with dec hashes). Furthermore, the `declare` command already prints the transaction hash in hex encoding.

Can you please unify the output to always use hex?

**Comment by karol-bisztyga** [comment]
LoL, sorry I didn't notice it's already done, I'm closing my PR 😅
