### ISSUE TITLE
Add `start_prank` cheatcode

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1341]

**Comment by kasperski95** [comment]
Should we rename this cheatcode to `prank` to be consistent with `roll` and `wrap`?
@MaksymilianDemitraszek @Arcticae

**Comment by MaksymilianDemitraszek** [comment]
@kasperski95 Not sure, current name is consistent with foundry:

**Comment by kasperski95** [comment]
Protostar's `roll` and `warp` aren't consistent with Foundry's equivalents. They can be cancelled, and they accept a target addresses similarly to Foundry's `startPrank`. Should we rename `roll` and `warp` to `startRoll` and `startWarp` then?

**Comment by Arcticae** [comment]
I'd rather have the simple names and have a `stopX` version instead, since we don't have the equivalent of one-time call (i doubt that it's something we'd like to have since users are acquainted with the current namings)

**Comment by MaksymilianDemitraszek** [comment]
I think foundry has a bit poor naming. Maybe we should just have `prank` as @Arcticae suggested?
