### ISSUE TITLE
Declare using the contract name doesn't work

### ISSUE THREAD

**Issue by karol-bisztyga** [software-mansion/protostar#1366]
It doesn't work with the new arch. Particularly, there's no ABI after this: https://github.com/software-mansion/protostar/blob/68a316eefd5e06d1a26470a6caa30e3f2bd86f43/protostar/compiler/project_compiler.py#L80

Repro branch: https://github.com/software-mansion/protostar/tree/kb/declare-by-name-repro

I might've done something wrong on the way, but wanted to report this as it may be a problem.

I used `deploy_contract` but this essentially comes down to the `declare` cheat code.

**Comment by Arcticae** [comment]
JFYI: This is an internal issue of our fixtures in tests
