### ISSUE TITLE
Add a documentation section for "Parametrized Tests" inside of "Tests"

### ISSUE THREAD

**Issue by Arcticae** [software-mansion/protostar#1430]
This section should explain which cheatcodes (`example` for now only) work for parametrizing tests. 
I think it's important to note that the section links to the example itself, but also showcases a few example flows.

People should also know that it's not connected to fuzzing in any way, but the docs should explain when to use what (and link to appropriate subpages)

**Comment by MaksymilianDemitraszek** [comment]
We do not support parametrized tests for cairo 1
