### ISSUE TITLE
Take care of TODO from `CheatableSysCallHandler`

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1456]
`protostar/cheatable_starknet/cheatables/cheatable_syscall_handler.py` has some leftover todos, we need to take care of them, I believe at least the one in the `_deploy` method is a bug.

Also please include a test which fail this scenario.

**Comment by Arcticae** [comment]
There are 3 TODOs in the file:
1. Addressed by #1460 (mock call)
2. Addressed by #1363 (expect call)
3. Will get addressed by a PR linked to this issue, with a failing test
