### ISSUE TITLE
`get_caller_address` behavior using `start_prank` with target_contract_address

### ISSUE THREAD

**Issue by notV4l** [software-mansion/protostar#1462]
| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | 0.9.1 |
| Cairo-lang | 0.10.3 |
| Git        | 2.34.1        |

There is 2 contracts : main & secondary
we call main.start using start_prank

%{ stop_prank = start_prank(ids.admin, target_contract_address=ids.main) %}
    IMain.start(main,secondary);
%{ stop_prank() %}

## Current Behavior
1. main call secondary
2. secondary callback main
3. get_caller_address returns admin address

## Expected Behavior
1. main call secondary
2. secondary callback main
3. get_caller_address returns secondary address

## Steps to Reproduce
simple test repo :
https://github.com/notV4l/protostar-get_caller_address

**Comment by MaksymilianDemitraszek** [comment]
Hi, thanks for reporting the issue ❤️ 

`start_prank` globally mocks the `get_caller_address` value for a given contract, I believe the behaviour is desired. Do you think it should only work only for the contract which called `start_prank`, not sure if I see the benefits of this behaviour as it limits possible scenarios you can model. Can you give me a scenario you cannot test with current approach and which could be tested with behaviour you suggested?

**Comment by notV4l** [comment]
from docs https://www.cairo-lang.org/docs/hello_starknet/user_auth.html

`get_caller_address()` returns the address of the source contract that called this contract. It can be the address of the account contract or **the address of another contract (if the function was invoked by another contract)**. When the contract is called directly (rather than through a contract), the function returns 0.

behavior should respect what function is supposed to do.
`start_prank ` is just a way to say i want to call this contract with this account it should not change the logic of how `get_caller_address` behaves

ex:
pranked Account calls contractA
contractA calls contractB
contractB calls contractA
contractA want to ensure caller is contractB

**Comment by MaksymilianDemitraszek** [comment]
We probably won't support it for cairo0 but we will investigate adding it to the cairo1 test runner once prank will be supported

**Comment by MaksymilianDemitraszek** [comment]
Should be solved by https://github.com/software-mansion/protostar/issues/1949
