### ISSUE TITLE
Remove higher order functions from scoped cheatcodes

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1471]
We should introduce `stop_` functions instead, this task includes checking if we have any cheatcodes in new arch which do that

**Comment by Arcticae** [comment]
There is only one cheatcode that uses returning callback: `stop_prank`

There also probably should be a "stop" variants of:
- expect_events (this one is kind of iffy but i believe it would be useful for creating more intricate test flows)
- mock_call (we did not have this before i believe, and i think this should probably be cancellable?)
- prank (mentioned above, implementation unchanged from previous one)

@MaksymilianDemitraszek thoughts?

**Comment by MaksymilianDemitraszek** [comment]
> expect_events (this one is kind of iffy but i believe it would be useful for creating more intricate test flows)
I believe there is no point in current flow, we just execute it at the end of the test as a leftover from the old testing flow (we may want to change that but it is a bigger, separate task)

**Comment by MaksymilianDemitraszek** [comment]
> expect_events (this one is kind of iffy but i believe it would be useful for creating more intricate test flows)

I believe there is no point in current flow, we just execute it at the end of the test as a leftover from the old testing flow (we may want to change that but it is a bigger, separate task)

> mock_call, prank

Yup, agreed

**Comment by Arcticae** [comment]
OK - i will create a task for each of those, and remove `prank` callback as an implementation for this task.
