### ISSUE TITLE
Implement `stop_expect_events`

### ISSUE THREAD

**Issue by Arcticae** [software-mansion/protostar#1482]
This could be named something else (`assert_expected_events` would be nice as well?). Decision about the name is in the scope of this task.

See [this](https://github.com/software-mansion/protostar/issues/1471) discussion for more context on the purpose and implementation.

**Comment by MaksymilianDemitraszek** [comment]
Moving it to improvements as it is out of initial scope

**Comment by MaksymilianDemitraszek** [comment]
It should be implemented while implementing #1476 if necessary
