### ISSUE TITLE
Add e2e testing for building for cairo1

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1494]
blocked by #1492

**Comment by Arcticae** [comment]
@MaksymilianDemitraszek we do have 
https://github.com/software-mansion/protostar/blob/4e31565fc530d74a55aa3b72f421706aec1089c5/tests/e2e/cairo1/test_building.py#L8

Do you mean something more intricate than that?

**Comment by MaksymilianDemitraszek** [comment]
@karol-bisztyga please reopen this one if it is not finished

**Comment by karol-bisztyga** [comment]
We have a simple test for this so I guess we can keep this one closed.
