### ISSUE TITLE
Redesign expect call hint

### ISSUE THREAD

**Issue by karol-bisztyga** [software-mansion/protostar#1509]
Raised in https://github.com/software-mansion/protostar/pull/1481#discussion_r1107003428

For now, the design looks like this:
```
expect_call(addr, "increase_balance_with_multiple_values", [1, 2, 3, 4])
stop_expect_call(addr, "increase_balance_with_multiple_values", [1, 2, 3, 4])
```
I suppose the point is to have something like this:
```
handle = expect_call(addr, "increase_balance_with_multiple_values", [1, 2, 3, 4])
stop_expect_call(handle)
```

**Comment by MaksymilianDemitraszek** [comment]
Actually this is pretty smart, 🚀

**Comment by karol-bisztyga** [comment]
I changed the title from `Redesign expect call hint to return a handle` to `Redesign expect call hint` because there's yet another idea from @Arcticae for redesigning this => https://github.com/software-mansion/protostar/pull/1501#discussion_r1114123210.

In his opinion `assert_expect_call` should throw if we assert a never-expected call, that was the original motivation for the idea.

You can check the link above, basically, we may consider redesigning `assert_expect_call` as well.
