### ISSUE TITLE
Validate `protostar.toml` against declared `protostar_version`

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#151]
As a Protostar dev, I want to tell the user to update the Protostar if the declared `protostar_version` is newer, so that the Protostar won't crash if we change `protostar.toml` structure in the future version.

**Comment by Arcticae** [comment]
@kasperski95 should we assume that we're going to be backwards-compatible? If we're not, we should probably exit with error on older file version

**Comment by mkaput** [comment]
As for now, I would simply raise an error, given that we are still very experimental, and the user base is manageably small.
