### ISSUE TITLE
Improve the way of checking return values of cairo1 test functions

### ISSUE THREAD

**Issue by karol-bisztyga** [software-mansion/protostar#1519]
Raised in https://github.com/software-mansion/protostar/pull/1507#discussion_r1111711631

We should replace `runner.get_return_values(3)[0]` with a code that will automatically read these values.
`CairoFunctionRunner::run()` does that but we cannot use it since we don't have `identifiers` (a member of the `program`). I thought we could maybe pass them somehow from rust code and found that rust uses `signatures` - that may be equivalent but I'm not sure.

**Comment by MaksymilianDemitraszek** [comment]
related
#1550

**Comment by MaksymilianDemitraszek** [comment]
We would like to use approach from the pr https://github.com/software-mansion/protostar/pull/1557

**Comment by Arcticae** [comment]
@MaksymilianDemitraszek closing this in favour of #1550

**Comment by karol-bisztyga** [comment]
I think this issue is different than #1550 and we shouldn't close it. In #1550 we want to identify if tests failed or not in different places regardless of what we use underneath to determine this. Here, we want to improve the way of checking the memory after a run (`runner.get_return_values(3)[0]` - Please, note that we still use this line in #1550).

**Comment by Arcticae** [comment]
This is not going to be needed because of the typechecking we do on tests, so this should be pretty stable way to do things, unless we migrate away from the blank return types in tests (which in my mind shouldn't happen anytime soon).
