### ISSUE TITLE
Deploy bug

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1531]
![image](https://user-images.githubusercontent.com/32527780/221196842-6d6e1b5d-bf4f-48a4-87ba-4df87e08d0bc.png)
https://discord.com/channels/793094838509764618/964116575387021413/1077954210303320174

**Comment by piotmag769** [comment]
The only way I could replicate it was by adding zero width space characters.

<img width="572" alt="Screenshot 2023-02-27 at 10 01 24" src="https://user-images.githubusercontent.com/56825108/221519410-f0ab1160-52a9-4612-a2cf-4664446ef01e.png">

It's such a rare case that I don't think we should change the code to warn users about it.
