### ISSUE TITLE
Unexpected Protostar error

### ISSUE THREAD

**Issue by Heroinru** [software-mansion/protostar#1533]
[

## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `PROTOSTAR_VERSION`  |
| Cairo-lang | `CAIRO_LANG_VERSION` |
| Git        | `GIT_VERSION`        |

## Steps to Reproduce

1.
2.
3.

**Comment by MaksymilianDemitraszek** [comment]
Unfortunately there are not actionable information in task description, closing. Feel free to add more information nd reopen
