### ISSUE TITLE
Poor error missing cairo path content

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1541]
```
E                   AssertionError: Proces exited with 1 while expected 0.",
E                   Args: protostar --cairo1 test tests
E                   Output:
E                   Traceback (most recent call last):
E                     File "binary_entrypoint.py", line 79, in <module>
E                     File "binary_entrypoint.py", line 23, in init
E                     File "protostar/start.py", line 21, in main
E                     File "protostar/start.py", line 47, in run_protostar
E                     File "protostar/start.py", line 42, in run_protostar
E                     File "asyncio/runners.py", line 44, in run
E                     File "asyncio/base_events.py", line 647, in run_until_complete
E                     File "protostar/protostar_cli.py", line 85, in run
E                     File "protostar/protostar_cli.py", line 126, in _run_command_from_args
E                     File "protostar/argument_parser/cli_app.py", line 25, in run
E                     File "protostar/commands/test/test_command.py", line 167, in run
E                     File "protostar/commands/test/test_command.py", line 247, in test
E                     File "protostar/testing/test_collector.py", line 149, in collect
E                     File "protostar/testing/test_collector.py", line 254, in _build_test_suites_from_test_suite_info_dict
E                     File "protostar/cairo_testing/cairo1_test_collector.py", line 43, in _build_test_suite_from_test_suite_info
E                     File "protostar/testing/test_collector.py", line 273, in _build_test_suite_from_test_suite_info
E                     File "protostar/cairo_testing/cairo1_test_collector.py", line 26, in collect_cairo1_tests_and_cache_outputs
E                     File "protostar/cairo/cairo_bindings.py", line 32, in collect_tests
E                   RuntimeError: Failed to build database
E                   [59765] Failed to execute script 'binary_entrypoint' due to unhandled exception!
E                   Unexpected Protostar error. Report it here:
E                   https://github.com/software-mansion/protostar/issues
```

Protostar raises ugly error when cairo_path content is missing, we need to update this error to be more readble

**Comment by karol-bisztyga** [comment]
I'm not sure if that entirely solves the problem, but I came up with something like this: https://github.com/software-mansion-labs/cairo/pull/23

That definitely helps and we should merge this but if that does not solve your problem, we can go further with this. In such a case, please specify what exactly you're expecting to see.

The PR I did replaces `RuntimeError: Failed to build database` with something more precise, for example: `Failed to build database: Failed to find development corelib.`

**Comment by MaksymilianDemitraszek** [comment]
It is better, but we should also do this
https://github.com/software-mansion-labs/cairo/pull/23#pullrequestreview-1318104296

**Comment by karol-bisztyga** [comment]
> @karol-bisztyga `Failed to add cairo path` in test collecting is also an issue, cannot be caught and handled in a proper manner from protostar. This might be worth addressing in the same PR

Good point, I already merged the branch I mentioned but we can (and should) address the problem you brought up as well.

**Comment by karol-bisztyga** [comment]
I looked into this and the specific errors are actually printed but not next to this `Failed to add cairo path` (they are above) because they're handled using [callbacks](https://github.com/software-mansion-labs/cairo/blob/386a93ffab81e6ffe0de903ca8dbb8e08342bdb7/crates/cairo-lang-compiler/src/diagnostics.rs#L46). I think we could just add a note there like "for a detailed information, please go through the logs above" and maybe additional information in the callbacks like `eprint!("Detailed error information: {diagnostic}");`.

**Comment by karol-bisztyga** [comment]
https://github.com/software-mansion-labs/cairo/pull/24

**Comment by MaksymilianDemitraszek** [comment]
#1490 Is this one a duplicate @karol-bisztyga ?

**Comment by karol-bisztyga** [comment]
Not exactly, it's a subset but we can close the one you mentioned and track all the work here.
