### ISSUE TITLE
`test-cairo1` extensive testing

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1544]
We need to test
- [x] glob querying
- [x] ignore command
- [x] `::test_case_name` syntax
- [ ] `no-progress-bar` (probably impossible to test, but leaving it here)
- [x] `exit-first`
- [ ] `report-slowest-tests` (probably impossible to test, but leaving it here)
- [x] `last-failed`

**Comment by MaksymilianDemitraszek** [comment]
Some of the tests can be e2e as well

**Comment by Arcticae** [comment]
Partially blocked by #1550
