### ISSUE TITLE
Consider redesigning mock call hint local

### ISSUE THREAD

**Issue by karol-bisztyga** [software-mansion/protostar#1554]
Inspired by https://github.com/software-mansion/protostar/issues/1509

`stop_mock_call` hint local isn't implemented yet - https://github.com/software-mansion/protostar/issues/1483 - but for now, it would look like this probably:
```
mock_call(target_address=123, entrypoint="foo", response=[1, 2, 3])
stop_mock_call(target_address=123, entrypoint="foo")
```

The idea here would be to return a handle, so it would look like this:
```
handle = mock_call(target_address=123, entrypoint="foo", response=[1, 2, 3])
stop_mock_call(handle=handle)
```

**Comment by MaksymilianDemitraszek** [comment]
Closing in favour of #1829
