### ISSUE TITLE
Investigate if we need to create project files

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1576]
https://github.com/software-mansion/protostar/blob/5aa0065c48721d958c28daca0534d2145bab683a/tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test.py#L43

Why it is necessary to create those files?
cc @Arcticae

**Comment by Arcticae** [comment]
The project is not loadable otherwise (adding cairo path fails), @karol-bisztyga can have more context on this

**Comment by MaksymilianDemitraszek** [comment]
Checked, it is a bug, created #1580
