### ISSUE TITLE
`Example` cheatcode doesn't work without `given` cheatcode 

### ISSUE THREAD

**Issue by abulenok** [software-mansion/protostar#1577]
## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `0.9.1`  |
| Cairo-lang | `0.10.3` |
| Git        | `2.37.1 (Apple Git-137.1)`        |

## Current Behavior

The `example` cheatcode doesn't pass arguments to a tested function when used without the `given` cheatcode. The test passes, printing warning:
```
protostar/testing/environments/fuzz_test_execution_environment.py:196: RuntimeWarning: coroutine 'FuzzTestExecutionEnvironment.build_and_run_test.<locals>.test' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

## Expected Behavior

The `example` cheatcode parametrizes test with explicitly provided data.

## Steps to Reproduce

This test should fail, but it doesn't
```
%lang starknet

@external
func setup_example_cheatcode() {
    %{ example(a = 12) %}
    return ();
}

@external
func test_example_cheatcode{syscall_ptr: felt*, range_check_ptr}(a: felt) {
    %{ print("TESTING STDOUT", ids.a) %}
    assert a = 14;
    return ();
}
```

This one fails as expected
```
%lang starknet

@external
func setup_example_cheatcode() {
    %{ 
    example(a = 12)
    given(a=strategy.integers(14, 14))
    %}
    return ();
}

@external
func test_example_cheatcode{syscall_ptr: felt*, range_check_ptr}(a: felt) {
    %{ print("TESTING STDOUT", ids.a) %}
    assert a = 14;
    return ();
}
```

**Comment by piotmag769** [comment]
Seems like async/await problem:

protostar/testing/environments/fuzz_test_execution_environment.py:204: RuntimeWarning: coroutine 'FuzzTestExecutionEnvironment.build_and_run_test.<locals>.test' was never awaited

Omw to fix it.

**Comment by MaksymilianDemitraszek** [comment]
@piotmag769 Can we restrain from fixing this for now 🥺 ? fuzzing is not our priority for now

**Comment by piotmag769** [comment]
@MaksymilianDemitraszek I think @Arcticae fixed it already
