### ISSUE TITLE
``category:Ideas @3022819432= [category:Ideas @3022819432= ](category:Ideas @3022819432= )

### ISSUE THREAD

**Issue by Montyc666** [software-mansion/protostar#1578]
``category:Ideas @3022819432= [category:Ideas @3022819432= ](category:Ideas @3022819432= )

_Originally posted by @Montyc666 in https://github.com/software-mansion/react-native-reanimated/issues/4177#issuecomment-1457740545_

**Comment by Arcticae** [comment]
This seems unrelated to this project. Please post in https://github.com/software-mansion/react-native-reanimated
