### ISSUE TITLE
Improve bindings workflow and dev docs

### ISSUE THREAD

**Issue by Arcticae** [software-mansion/protostar#1598]
- [ ] We need to add a step in bindings installation script, to initialize repo submodules before installing the bindings
- [ ] We need to improve documentation on how to checkout branch from the submodule if developing with branch other than master/main
- [ ] After locally checking out a branch (in `protostar/cairo`), the `install_cairo_bindings.sh` pulls the master branch

**Comment by MaksymilianDemitraszek** [comment]
Adding it to current milestone, I believe the bindings installation flow should be flawless to not block developers
