### ISSUE TITLE
Rename for cairo1 build command argument `cairo-path` to `linked-libraries`

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1604]
For the sake of consistency with cairo1-test-command

**Comment by karol-bisztyga** [comment]
To whoever will take this task, please go through the docs as well.

**Comment by abulenok** [comment]
> To whoever will take this task, please go through the docs as well (website/docs/tutorials/08-cairo-1-support/03-compiling.md)

@karol-bisztyga I don't see `website/docs/tutorials/08-cairo-1-support/03-compiling.md` file on `master`

**Comment by karol-bisztyga** [comment]
I wrote this assuming that https://github.com/software-mansion/protostar/pull/1643 was about to be merged but in the meantime we decided to postpone that one.
