### ISSUE TITLE
Improve cairo1 template structure

### ISSUE THREAD

**Issue by Arcticae** [software-mansion/protostar#1607]
https://github.com/software-mansion/protostar/pull/1603#discussion_r1135600727

We should modify the structure of the template to have `cairo_project.toml` at the root, and crate should be named with the provided project name instead of `src`.

**Comment by MaksymilianDemitraszek** [comment]
We probably should investingate it deeper and in cooperation with scarb team. We discussed it on slack, for person picking up this task, lmk I will refer you to the disussion.

**Comment by cptartur** [comment]
> We should modify the structure of the template to have `cairo_project.toml` at the root, and crate should be named with the provided project name instead of `src`.

Both of these changes are already present in master branch. We can update the contracts content to reflect real contracts better than current fib and add some examples of hint local usages.

Otherwise it's should be good.
