### ISSUE TITLE
Add `deploy_contract` to cairo-protostar

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1620]
It should be a helper function calling decalre, prepare, deploy in a sequence under the hood. It should be implemented in cairo1 and added to cheatcodes corelib, no changes on protostar side are needed nor in compilers code.

**Comment by MaksymilianDemitraszek** [comment]
@Radinyn Is this one done? If it is, please close it

**Comment by Radinyn** [comment]
Cairo functionality is done, but it's not yet tested in Protostar.

**Comment by MaksymilianDemitraszek** [comment]
@Radinyn Can we add those test to close it 🙏
