### ISSUE TITLE
Investigate a possibility to reuse code in cairo fork hint locals

### ISSUE THREAD

**Issue by karol-bisztyga** [software-mansion/protostar#1644]
Raised in https://github.com/software-mansion-labs/cairo/pull/43.

It may be good to check if we can write some reusable code for the hint local code in https://github.com/software-mansion-labs/cairo/blob/e4b3f34146727682ee5556cc7fb40ea7f9384da7/crates/cairo-lang-casm/src/hints/mod.rs so we could be able to parse the arguments in a better way.

**Comment by Arcticae** [comment]
I think it's not worth adding the complexity + effort to investigate implementing this
cc @MaksymilianDemitraszek
