### ISSUE TITLE
Test `deploy_contract_cairo0` corelib func

### ISSUE THREAD

**Issue by Arcticae** [software-mansion/protostar#1645]
We need to add it to `cairo-protostar`, signatures should match the standard non-cairo0 ones. 

We need to have this distinction, because the implementation underneath should be different than the new cairo1

Libfunc can be implemented straight away, with interfaces based off existing ones

Other ones need to be integration tested on top of https://github.com/software-mansion/protostar/pull/1636

Integration tests can (and should) be based on the [deleted tests](https://github.com/software-mansion/protostar/pull/1561/files) from the old runner

**Comment by MaksymilianDemitraszek** [comment]
@piotmag769 We only need `deploy_contract` can we update task description
