### ISSUE TITLE
Adapt protostar cli to Starknet 0.11

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1654]
We need to provide a cli equivalent with Starknet's cli

It might be splitted into separate tasks

**Comment by MaksymilianDemitraszek** [comment]
It is blocked by starknet.py update, @cptartur can probably provide more information on this

**Comment by cptartur** [comment]
0.15.0 of starknet.py has been released on pypi, so we can start integrating with it directly. Note that `Contract` API is not compatible with cairo1 contracts as of this version.
