### ISSUE TITLE
Add `call` cheatcode implementation in cairo1

### ISSUE THREAD

**Issue by karol-bisztyga** [software-mansion/protostar#1680]
We need to make the `call` cheatcode work in cairo1 and add integration tests for it.

This task being finished means
- a test that declares contract passes
- a test that fails to declare a contract provides proper error code

This one should point into https://github.com/software-mansion/protostar/pull/1526

**Comment by cptartur** [comment]
I think, it mostly requires testing. Cairo1 didn't introduce any big changes to invoking and calling contracts so it should be working.
