### ISSUE TITLE
Produce both sierra json and casm when building a project

### ISSUE THREAD

**Issue by cptartur** [software-mansion/protostar#1684]
When running `protostar build-cairo1`, both sierra json and casm compiled contracts should be produced.

Outputs should be exactly equivalent to running
`cargo run --bin starknet-compile -- /path/to/input.cairo /path/to/output.json` and `cargo run --bin starknet-sierra-compile -- /path/to/input.json /path/to/output.casm` in new cairo compiler.

**Comment by MaksymilianDemitraszek** [comment]
This is not a critical feature as declare will handle compilation under the hood, I am moving it back to next milestone. Let me know it that is an issue
