### ISSUE TITLE
Fix stale `ProtostarFixture` configuration file issue

### ISSUE THREAD

**Issue by Arcticae** [software-mansion/protostar#1689]
Protostar fixture needs to be able to recognise changes made to the `.toml ` (adding contracts, etc) and be able to reload config file in subcommands, so i.e. contracts are not stale.

Example:
https://github.com/software-mansion/protostar/pull/1526#discussion_r1151878758_

**Comment by abulenok** [comment]
@Arcticae what is the expected behavior?

**Comment by Arcticae** [comment]
@abulenok ideally, after adding a contract through `ProtostarFixture.add_contracts`, `protostar.toml` should be reloaded in the fixture, meaning i.e. fresh construction of the config file object and rebuilding the command objects inside the `ProtostarFixture`.
