### ISSUE TITLE
Remove support for gateway in whole protostar. Add warnings for using gatway.

### ISSUE THREAD

**Issue by Arcticae** [software-mansion/protostar#1695]

**Comment by MaksymilianDemitraszek** [comment]
@Arcticae Why to add warnings? Isn't this an implementation detail of starknet.py? Can you elaborate on this?

**Comment by Arcticae** [comment]
We don't support using full node as of now, the logic is hardcoded to use `GatewayClient`. It should be investigated, not sure if and which parameters would change when migrating to `FullNodeClient`. There might also be a need to provide new ones.

**Comment by MaksymilianDemitraszek** [comment]
Should be taken into account #1948
