### ISSUE TITLE
Investigate how to properly use arrays in cairo1

### ISSUE THREAD

**Issue by karol-bisztyga** [software-mansion/protostar#1717]
Raised in https://github.com/software-mansion/protostar/pull/1716#discussion_r1157061582

When writing tests for `deploy`, I encountered the following error:
```
error: Variable was previously moved. Trait has no implementation in context: core::traits::Copy::<core::array::Array::<core::felt252>>
```
I tried to come up with a minimal repro, but something like this seems to work:
```
let mut arr = ArrayTrait::new();
arr.append(1);
arr.append(2);
assert(arr.len() == 2_u32, 'check len');
assert(arr.len() == 2_u32, 'check len');
let x = PreparedContract {
    contract_address: 123,
    class_hash: 123,
    constructor_calldata: arr
};
drop(x);
```
I'm leaving this in such a state, we should investigate why `len` doesn't work for us in the `deploy` test and how to make it work.

**Comment by MaksymilianDemitraszek** [comment]
Closing, follow up task #1846
