### ISSUE TITLE
Handle error messages in hint locals properly

### ISSUE THREAD

**Issue by karol-bisztyga** [software-mansion/protostar#1725]
The reference is here:
https://github.com/software-mansion/protostar/pull/1716#discussion_r1159403968
The explanation of the problem:
https://github.com/software-mansion/protostar/pull/1716#discussion_r1159419205

**Comment by karol-bisztyga** [comment]
The error message that inspired me to implement a hash solution in the linked PR, which eventually lead to raising this issue is:
```
"(500, {'code': <StarknetErrorCode.TRANSACTION_FAILED: 52>, 'message': 'Execution was reverted; failure reason: [0x70616e6963].'})"
```
We get this as a string, the real message is in the dict that is in the tuple and can be accessed by the field `message`. My concern is that parsing such a string can be slow and error-prone, we should investigate what errors we receive exactly and if we can generically parse them to pull the target message.
Also, I think we should always fall back as we may one day get an error we've never got before.
Another thing is, even if we pull the target `message`, it may very likely also contain a 31+ long prefix, even here we have `Execution was reverted; failure reason:`, which is 39-character long.
The problem with these prefixes is that we're not able to distinguish errors from each other, therefore we're not really able to say what exactly went wrong.

I think we should investigate these errors and come up with a solution. There are two main goals here:
- allow users to check error messages instead of checking some cryptic long numbers - in the linked PR (at a current state) the hash of the error message is being calculated so if a user wants to check if the proper error has been raised, they have to do something like this:
 ```
assert(err == 179143216683939089435778763860492020889796834434088318742252478611012859956, 'proper error thrown');
 ```
This is not handy at all.
- allow a user to handle every error separately, so if we have three errors like these:
 ```
"Execution was reverted; failure reason: invalid argument"
"Execution was reverted; failure reason: invalid number of arguments"
"Execution was reverted; failure reason: invalid contract address"
 ```
with the 31-length constraint, for every one of them we end up with this: `"Execution was reverted; failure"`
So if a user checks for `Execution was reverted; failure` they never know what exactly went wrong.

**Comment by Arcticae** [comment]
I'm throwing this into the next milestone since it's virtually impossible to debug a contract with the current solution, we should provide at least a partial workaround (output in the console?) somehow, before the release of this functionality.

cc @MaksymilianDemitraszek

**Comment by karol-bisztyga** [comment]
Maybe related https://github.com/software-mansion/protostar/issues/1731

**Comment by karol-bisztyga** [comment]
After this is discussed and we make a decision on how to handle this, we should go through all the cairo1 tests and see if we should assert any error messages there.

**Comment by MaksymilianDemitraszek** [comment]
The behaviour of error codes should be
Having a contract
```
Contract {
    #external
    funcA {
       panic('some error 'msg')
    }
}
```
Corresponding test should be 
```
test_contract {
  match call {
   OK => panic
   Err('some error 'msg') => _
  }
}
```

Other errors should be just raised as standard python errors
