### ISSUE TITLE
Support user scripts in `protostar.toml`

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#173]
- `protostar`, `cairo-compile` and `starknet` should be available for scripts
- allow defining PATH for scripts in form of list of globs
- allow overwriting `install`, `update`, `remove` to use different package manager from protostar
- add command aliases, e.g., `add` instead of `install`

**Comment by MaksymilianDemitraszek** [comment]
@mkaput I think this task is about creating the same system of custom command the `npm` has. So you can run `protostar run deploy_custom`. I think this task is no more relevant and we should close it.

**Comment by mkaput** [comment]
In that context -- I agree
