### ISSUE TITLE
Deprecate `cairo_project.toml` in favour of `Scarb.toml`

### ISSUE THREAD

**Issue by piotmag769** [software-mansion/protostar#1737]
We should deprecate `cairo_project.toml` and use `Scarb.toml` instead.
The most reasonable way to do it is change the format of the argument `linked_libraries`/`cairo_path` in Protostar and related  `maybe_cairo_paths` in the compiler + change the way `ProjectConfig` is built in the compiler.

TODO in the same PR:
- [x] #1815
- [x] #1898

**Comment by MaksymilianDemitraszek** [comment]
@piotmag769 Can please elaborate a bit what has to be done and why?

**Comment by MaksymilianDemitraszek** [comment]
We should update scarb template

**Comment by MaksymilianDemitraszek** [comment]
We should also update docs
