### ISSUE TITLE
Consider handling named arguments in cairo1

### ISSUE THREAD

**Issue by karol-bisztyga** [software-mansion/protostar#1754]
Source: https://github.com/software-mansion/protostar/pull/1726#discussion_r1164371561

I think we should consider handling named arguments in cairo1, particularly in the `call` hint local, and maybe others as well. For now, we only allow passing arguments as an array of felts.

**Comment by Arcticae** [comment]
I think either way this will not impact data transformation, which snippet references this issue. 
We could consider some cairo tricks to make it easier to pass arguments though.

**Comment by MaksymilianDemitraszek** [comment]
This is on the roadmap https://github.com/orgs/software-mansion-labs/projects/3?pane=issue&itemId=26086101
but i am not sure if it a high priority rn

**Comment by MaksymilianDemitraszek** [comment]
It will be supported on cairo level, closing in favour of  #1823
