### ISSUE TITLE
Investigate differences in gas support between `quaireaux` and `protostar`

### ISSUE THREAD

**Issue by piotmag769** [software-mansion/protostar#1767]
They seem to be using [this](https://github.com/keep-starknet-strange/quaireaux/blob/main/quaireaux/utils/src/utils.cairo):
```cairo
#[inline(always)]
fn check_gas() {
    match gas::withdraw_gas_all(get_builtin_costs()) {
        Option::Some(_) => {},
        Option::None(_) => {
            let mut data = ArrayTrait::new();
            data.append('Out of gas');
            panic(data);
        }
    }
}
```

Meanwhile in our tests we use [this](https://github.com/software-mansion/protostar/blob/master/tests/integration/cairo1/gas_test/test.cairo#L5):
```cairo
    match gas::withdraw_gas() {
        Option::Some(_) => {},
        Option::None(_) => {
            let mut data = ArrayTrait::new();
            data.append('Out of gas');
            panic(data);
        }
    }
```

`withdraw_gas_all(get_builtin_costs())` causes [this]() e2e test using quaireaux as dependency fail.

**Comment by Arcticae** [comment]
Isn't this something from alpha-7?

**Comment by piotmag769** [comment]
> Isn't this something from alpha-7?

No idea honestly.
cc @MaksymilianDemitraszek

**Comment by MaksymilianDemitraszek** [comment]
No idea as well

**Comment by MaksymilianDemitraszek** [comment]
Investigate if it still relevant

**Comment by cptartur** [comment]
Funny enough, `gas::withdraw_gas_all(get_builtin_costs())` is used in multiple places in the cairo1 compiler repository, so I wonder why this fails.
