### ISSUE TITLE
Add `fee` cheatcode

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#178]
```solidity
cheats.fee(25 gwei);
emit log_uint(block.basefee); // 25000000000
```

**Comment by MaksymilianDemitraszek** [comment]
Closing in favour of #796

**Comment by kasperski95** [comment]
@MaksymilianDemitraszek 
What if a user wants to create a fee assertion?

**Comment by MaksymilianDemitraszek** [comment]
I don't see a value from such feature. I think printed information is sufficient. Asserting steps would only result in user having to bump it each time they introduce a new change.
