### ISSUE TITLE
Add `addr` cheatcode

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#179]
Computes the address for a given private key.

```solidity
address alice = cheats.addr(1);
emit log_address(alice); // 0x7e5f4552091a69125d5dfcb7b8c2659029395bdf
```

**Comment by MaksymilianDemitraszek** [comment]
Is this relevant in starknet context?

**Comment by kasperski95** [comment]
It might be useful if we add support for testing signing.

**Comment by kasperski95** [comment]
Internal discussion: a user can import a function from the starknet
