### ISSUE TITLE
Proxy tests for cheatcodes

### ISSUE THREAD

**Issue by karol-bisztyga** [software-mansion/protostar#1794]
I heard the word that in Cairo 1 we should use `replace_class` for proxy but I couldn't find any concrete examples so far.

May be helpful: https://github.com/Dev43/aa-cairo1

**Comment by cptartur** [comment]
I think old proxy pattern should work exactly the same as it did in cairo0 assuming all required syscalls are already available.

Or you can basically define an `upgrade` method on your contract that calls `replace_class` and use that instead of proxy pattern

```cairo
#[external]
fn upgrade(new_contract_class: ClassHash) {
  // do some kind of owner verification
  replace_class_syscall(new_contract_class);
}
```

**Comment by MaksymilianDemitraszek** [comment]
@karol-bisztyga What was the purpose of this issue? Do we need to write any proxy tests?

**Comment by karol-bisztyga** [comment]
Yes, the point is to have proxy Cairo 1 tests.

**Comment by MaksymilianDemitraszek** [comment]
Duplicate of https://github.com/software-mansion/protostar/issues/1383
