### ISSUE TITLE
`start_spoof` cheatcode

### ISSUE THREAD

**Issue by Arcticae** [software-mansion/protostar#1806]
We should be able to provide message signature from `get_tx_info` syscall in tests, in order to enable testing accounts

**Comment by cptartur** [comment]
Work on compiler side should already be mostly done (see linked PR). We've decided to continue working on python implementation later. Moving back to backlog

**Comment by abulenok** [comment]
`start_spoof` allows mocking TransactionInfo returned by `get_tx_info` (https://github.com/starkware-libs/cairo/blob/main/corelib/src/starknet/info.cairo#L61)
`stop_spoof` removes this mocking
