### ISSUE TITLE
Deprecate `--linked-libraries`

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1815]
After we have a proper support for `Scarb.toml` we can deprecate this argument

**Comment by MaksymilianDemitraszek** [comment]
Blocked by #1737

**Comment by piotmag769** [comment]
I think it should be done together with deprecating `cairo_project.toml` (in the same PR).
It will stop working anyways since I'm changing the format of `linked_libraries`/`maybe_cairo_paths` argument that is passed to the compiler.
WDYT?

cc @MaksymilianDemitraszek
