### ISSUE TITLE
Validate `temporary solution`

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1825]
This line has been marked as a TODO 
mentioning being a temporary solution
https://github.com/software-mansion/protostar/blob/b00a6e90d807182bb199134795bb246e9c3a6424/protostar/commands/init/project_creator/_project_creator.py#L42

**Comment by piotmag769** [comment]
It should be closed with https://github.com/software-mansion/protostar/pull/1719

**Comment by MaksymilianDemitraszek** [comment]
@piotmag769 can you ensure we remove TODO in the relevant PR?
