### ISSUE TITLE
Add assume() and reject() cheatcodes

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#183]
```solidity
function assume(bool) external;
```

If the boolean expression evaluates to false, discard the current fuzz inputs and start a new fuzz run.

The assume cheatcode should mainly be used for very narrow checks. Broad checks will slow down tests as it will take a while to find valid values, and the test may fail if you hit the max number of rejects. You can configure the rejection thresholds by setting fuzz_max_local_rejects and fuzz_max_global_rejects in your foundry.toml file. More information on filtering via assume can be found here.

For broad checks, such as ensuring a uint256 falls within a certain range, you can bound your input with the modulo operator or Solmate's bound method.

```solidity
// Good example of using assume
function testX(uint256 a) public {
    cheats.assume(a != 1);
    require(a != 1);
    // [PASS]
}

// In this case assume is not a great fit, so you should bound inputs manually
function testY(uint256 a) public {
    a = bound(a, 100, 1e36);
    require(a >= 100 && a <= 1e36);
    // [PASS]
}
```

**Comment by mkaput** [comment]
Cairo boolean expressions syntax is limited on parser level to `if` state elements. Hence, I propose the following syntax:

```cairo
if a != 1 and b != 1:
    %{ fuzz.reject() %}
end
```

**Comment by mkaput** [comment]
Update, currently I propose following two cheatcodes:

```cairo
if a != 1 and b != 1:
    %{ reject() %}
end
```

and a shortcut:

```cairo
%{ assume(ids.a != 1 and ids.b != 1) %}
```

Both functions are exported by Hypothesis in their control module, so this feature should be trivial.
