### ISSUE TITLE
Consider unit testing approach in Cairo1 template

### ISSUE THREAD

**Issue by piotmag769** [software-mansion/protostar#1835]
Currently the template contract is basically tested using integration tests.
We want to encourage users to use unit testing to make tests efficient and faster.

Pic rel
<img width="476" alt="Screenshot 2023-04-25 at 13 19 24" src="https://user-images.githubusercontent.com/56825108/234261205-1a0ff487-d969-4ab8-8c4f-63f3a30d3719.png">

**Comment by MaksymilianDemitraszek** [comment]
I think template presents both approaches which is the best option, new docs clearly mention integration tests speed issue.
