### ISSUE TITLE
Change missleading `_build_contract` error message

### ISSUE THREAD

**Issue by piotmag769** [software-mansion/protostar#1838]
```
f"Multiple files found for contract {contract_name}, " 
f"only one file per contract is supported in cairo1!"
```
It is a problem of multiple contracts in one package, not multiple files.

**Comment by cptartur** [comment]
Actually we don't support either multiple contracts per package and contacts with multiple fails. Afaik cairo0 compilation in protostar allowed passing multiple files to be compiled as a single contract.

**Comment by cptartur** [comment]
Having multiple contracts defined one package and running `protostar build-cairo1` correctly produces an error like this:

```
14:43:09 [ERROR] Build failed
14:43:09 [ERROR] A runtime error occurred in binding compile_starknet_contract_to_sierra_from_path: Compilation unit must include only one contract.
```

Closing this now. Please reopen if you think this is still relevant.
