### ISSUE TITLE
Document that by default `get_caller_address` returns 0

### ISSUE THREAD

**Issue by piotmag769** [software-mansion/protostar#1885]
It is a feature of [`get_caller_address`](https://www.cairo-lang.org/docs/hello_starknet/user_auth.html#getting-the-caller-address) since new tests are no longer contracts. Would be nice to include an information that you could use `prank` to change caller address.

**Comment by MaksymilianDemitraszek** [comment]
I think we should describe this in Integration Testing section added in #1802, it should be described in an abstarct way (relationship between starknet code and test code), and give mentioned case as an example.

**Comment by MaksymilianDemitraszek** [comment]
Solved by #1892
