### ISSUE TITLE
Implement `declare` cheatcode for rust test runner

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1888]
We should implement `declare` cheatcode as a proving ground for other cheatcodes. It should declare cairo 1 contracts and use starknet in rust. It can be split into smaller tasks.

We probably should use https://github.com/lambdaclass/starknet_in_rust/blob/f4b80ed222381aea6e3f5a81047fa1c829d2fe97/crates/starknet-rs-py/src/starknet_state.rs#L35 to declare the contract.

We should build on 0.11 branch of starknet in rust.

We should use custon HintProcessor to handle cheatcode hints https://github.com/software-mansion-labs/cairo/blob/4094d447c77990142361f14b057f2e477a4d3130/crates/cairo-lang-runner/src/casm_run/mod.rs#L1315

**Comment by karol-bisztyga** [comment]
blocked by #2048
