### ISSUE TITLE
Document `RevertedTransaction` structure in integration testing section

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1899]
I think we should have `RevertedTransaction` documented somewhere. I think there is already some minimal either documentation on master or some open PR.

_Originally posted by @cptartur in https://github.com/software-mansion/protostar/pull/1892#discussion_r1190920510_

**Comment by Arcticae** [comment]
@MaksymilianDemitraszek isn't this one done?

**Comment by Arcticae** [comment]
`website/docs/cairo-1/05-testing/02-integration-testing.md`

**Comment by MaksymilianDemitraszek** [comment]
It mentions how to use it, but the structure itself isn't documented. cc @cptartur

**Comment by cptartur** [comment]
> It mentions how to use it, but the structure itself isn't documented. cc @cptartur

#1925 should address it
