### ISSUE TITLE
Rename `declare-cairo1` -> `declare` and `declare` -> `declare-cairo0`

### ISSUE THREAD

**Issue by piotmag769** [software-mansion/protostar#1937]

**Comment by MaksymilianDemitraszek** [comment]
@Arcticae probably left it on purpose? He can probably elaborate about this decision

**Comment by Arcticae** [comment]
@MaksymilianDemitraszek this wasn't included in the original plan of renaming stuff, but we decided to do it eventually, so renaming seems like a good way to go
