### ISSUE TITLE
Integrate with Rust CLI

### ISSUE THREAD

**Issue by karol-bisztyga** [software-mansion/protostar#1994]
For now, the rust test runner can be run from the old Python CLI. We eventually want to be able to run it from the rust CLI, so once the new CLI is ready, we should integrate the rust test runner with it and remove the bindings for the Python CLI.

blocked by https://github.com/software-mansion/protostar/milestone/43

**Comment by cptartur** [comment]
#1974 basically replaced the bindings with new CLI
