### ISSUE TITLE
Export cheatcodes as scarb package

### ISSUE THREAD

**Issue by cptartur** [software-mansion/protostar#1997]
Currently corelib is configured by setting a `CARGO_MANIFEST_DIR` environment variable. We should consider a better way of detecting the corelib.

Note: as of creation of this issue, corelib provided by scarb cannot be used. Protostar uses a modified corelib.

**Comment by MaksymilianDemitraszek** [comment]
Related issue #1614

**Comment by cptartur** [comment]
Possible solution for this: We could define a new scarb project in protostar repo containing only cheatcodes, instead of forking the corelib. Then it could be possible to use this package as a dependency in protostar projects. This way, cheatcodes would be loaded by scarb like a normal dependency would and we wouldn't have to handle detecting corelib at all.

**Comment by cptartur** [comment]
cc @mkaput

**Comment by Arcticae** [comment]
#2133 needs to be included in scope of this task
