### ISSUE TITLE
Deploying with dispatchers

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#2080]
Currently we use dedicated `deploy` cheatcode. We should move this logic to deploy syscall in `CairoHintProcessor` so we can use cario dispatchers to interact with contracts

**Comment by cptartur** [comment]
Can you provide a better description?

**Comment by MaksymilianDemitraszek** [comment]
Done

**Comment by MaksymilianDemitraszek** [comment]
This is not possible rn  -> #2101 , thus there is no use in doing this, closing
