### ISSUE TITLE
Require all tests to be defined inside `#[cfg(test)]` module

### ISSUE THREAD

**Issue by cptartur** [software-mansion/protostar#2092]
Currently, tests will be collected from all files in all directories within a package.

This logic should be changed so tests are only collected from modules marked with `#[cfg(test)]`.
Additionally, each file in `tests` directory should implicitly be treated as a separate module with `#[cfg(test)]` added - similarly to how `cargo test` works.

**Comment by Arcticae** [comment]
@mkaput/@maciektr know how to do it FYI

**Comment by piotmag769** [comment]
`cargo test` executes every function marked with `#[test]` attribute, `#[cfg(test)]` is just to prevent compiling code used for testing for dev/release builds. We currently support compiling code marked with `#[cfg(test)]` during tests anyways.
