### ISSUE TITLE
Normalize outputs in CLI

### ISSUE THREAD

**Issue by THenry14** [software-mansion/protostar#2107]
We should decide on one approach to outputting information to users, and apply it (Felts, Ints, formatting etc).

Suggestions: 
https://docs.rs/console/latest/console/
https://docs.rs/color-eyre/latest/color_eyre/

We could take a look at what scarb is using, and try to conform to that.

**Comment by piotmag769** [comment]
I would also emphasise on the need of returning non-zero exit code on failure - it will be useful in scripts and that's what we do in test runner as well.
cc @THenry14 @war-in
