### ISSUE TITLE
Normalize inputs for commands

### ISSUE THREAD

**Issue by THenry14** [software-mansion/protostar#2117]
We should follow inputs formats as closely as possible with foundry.
Let's start with call, and then go command by command (this task can be split, or all commands can be done under it)

https://book.getfoundry.sh/reference/cast/cast-call#examples

**Comment by MaksymilianDemitraszek** [comment]
@THenry14 I think we do not have to follow foundry strictly in such cases, we can improve upon interfaces if there is a space for improvement and I believe named args are an improvement for readability

**Comment by THenry14** [comment]
> I think we do not have to follow foundry strictly in such cases, we can improve upon interfaces if there is a space for improvement and I believe named args are an improvement for readability

@MaksymilianDemitraszek that's awesome news to hear, thanks for clarification ❤️

**Comment by karol-bisztyga** [comment]
ok closing
