### ISSUE TITLE
Create a crate for handling `starknet_artifacts.json` file from scarb

### ISSUE THREAD

**Issue by cptartur** [software-mansion/protostar#2141]
We're handling `starknet_artifacts.json` file both in the rust runner and CLI. Code for deserializing and handling this file could be moved to a separate crate and used in both these projects.

Should include swapping code parts in CLI/rust runner which parse the artifacts

**Comment by piotmag769** [comment]
Make sure to address https://github.com/software-mansion/protostar/pull/2138#discussion_r1245132360

**Comment by Arcticae** [comment]
For now, create a separate crate and we'll merge it into one workspace when we have a new repo

**Comment by piotmag769** [comment]
https://github.com/software-mansion/protostar/pull/2138#discussion_r1247776774
We should also implement better error messages for cases where a user changes the content of Scarb.toml (like removing `[[target.starknet-contract]]` or adding `sierra=false` to the starknet target
