### ISSUE TITLE
Make a PR to cairo repo to change `MemBuffer` visibility to public

### ISSUE THREAD

**Issue by cptartur** [software-mansion/protostar#2158]
From: https://github.com/software-mansion/protostar/pull/2144#discussion_r1246606530

`MemBuffer` from cairo repo https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-runner/src/casm_run/mod.rs#L394 should have it visibility changed to public so it can be used in our cheatcode hint processor.

**Comment by abulenok** [comment]
https://github.com/starkware-libs/cairo/pull/3588

**Comment by abulenok** [comment]
related https://github.com/software-mansion/protostar/issues/2164
