### ISSUE TITLE
Recursively search for test files when test target is a directory

### ISSUE THREAD

**Issue by Bernardstanislas** [software-mansion/protostar#240]
As a StarkNet smart contract developer, I want the test command to recursively look for my test files in the provided target directory.
This will help me better organize my tests in sub-directories.

**Comment by kasperski95** [comment]
I believe Protostar already does it.

https://user-images.githubusercontent.com/9629577/166728260-89bc9640-1322-4a6c-a134-3113c0920f3d.mov

**Comment by Bernardstanislas** [comment]
@kasperski95 you are right, I opened this issue in the first place because I thought protostar could not recursively search for tests, but it was actually due to a misuse.
All our test files were in fact named `test.cairo` which is not detected by protostar.
Thank you @AnthonyBuisset for pointing this out!
