### ISSUE TITLE
Make the package publishable

### ISSUE THREAD

**Issue by Bernardstanislas** [software-mansion/protostar#264]
As a StarkNet smart contract developer, I want to import the `protostar` package as a python dependency to use it in my tooling suite.

**Comment by kasperski95** [comment]
What Protostar functionality do you import? Rather than making this project publishable, I think we could extract that functionality to a separate package with proper API.
@MaksymilianDemitraszek thoughts?

**Comment by MaksymilianDemitraszek** [comment]
@Bernardstanislas Yea, protostar was intended to be used as a cli app not a python package. We are open to changing this if it would be useful but would be nice if you could elaborate on the description of your use case. This way we could address the issue the best way possible 😄

**Comment by Bernardstanislas** [comment]
Sure! Thanks for the interest in this issue :)
We are currently building a learning tool to get up and running with Cairo and the Starknet ecosystem, you can find out more in the [repo](https://github.com/onlydustxyz/starklings).

The idea is to make an interactive tutorial _à la_ [Rustlings](https://github.com/rust-lang/rustlings), to help onboard developers in the Starknet ecosystem.

We found out that Protostar is a perfect fit for what we have: plain Cairo files where the developer has to modify the code to make the tests pass.
Using protostar helps us write in-file tests, and benefit from the latest blazing fast tooling in the ecosystem.

Since Starklings itself is written in Python, we'd like to invoke Protostar test runner directly using the Python API. Since the package is not published yet, we spawn subprocesses to run the tool, which is not ideal.

Is the use case clearer with these explanations? 

I made the PR to make the repo publishable, IMHO there is no urgent need to change the structure of the published package, people will be able to pick whatever part they need for their project – the test runner in our case.

**Comment by kasperski95** [comment]
I am not convinced about making Protostar a python package because we don't offer/support a python API.

If you really want to use Protostar's internals in your project, you can use git submodules. Please be aware, that we are refactoring the code responsible for the testing (https://github.com/software-mansion/protostar/pull/250).

```
- submodules
   - protostar
     - src 
- src
   - foo.py (from submodules.protostar.src... import ...
  ```

**Comment by Bernardstanislas** [comment]
I tried this but there are conflicts of namespace since "src" was used as a root folder for all the source files. Actually my PR only renames this root folder to a `protostar` folder, in case we merge this one you are right that a submodule would work for us, without having to publish the package.
