### ISSUE TITLE
[BUG] protostar test command returns 0 even when some tests fails

### ISSUE THREAD

**Issue by ofux** [software-mansion/protostar#269]
It's hard to know if it is a bug or a feature request, but running `protostar test` should return a non-zero code when some tests fail, so it could be easily integrated in CIs. Indeed, most CIs (such as GitHub actions) fail when a command returns a non-zero code.

## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `0.2.0`  |
| Cairo-lang | `0.8.1` |
| Git        | `2.30.1`        |

## Current Behavior
`protostar test` command returns 0 even when some tests fails.

## Expected Behavior
`protostar test` command returns 1 when some tests fails.

## Steps to Reproduce
Run `protostar test` with some failing tests and check the return code: `echo $?`.

**Comment by MaksymilianDemitraszek** [comment]
We will try to address it in the next upcoming release

**Comment by ofux** [comment]
BTW, we have the same issue with **compilation**. Should I create a new issue?

**Comment by MaksymilianDemitraszek** [comment]
You can just edit the title of this one
