### ISSUE TITLE
Refactor args to be shared across commands if necessary

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#294]

**Comment by MaksymilianDemitraszek** [comment]
Do you remember what this issue is about @kasperski95?

**Comment by kasperski95** [comment]
Arguments like `cairo-path` could be moved to a separate file and be shared across many commands.

**Comment by mkaput** [comment]
@kasperski95 is this still relevant?

**Comment by kasperski95** [comment]
Slightly, it's not super-important. Closing.
