### ISSUE TITLE
Fix freezing when Protostar throws an unexpected error during tests

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#308]
Discovered when tried to raise `NotImplementedError` for `setup_state` hook.

**Comment by MaksymilianDemitraszek** [comment]
This is the same issue as #262, we should merge them into one

**Comment by kasperski95** [comment]
I think this is a different issue. I'll merge these task if the problem turns out to be the same.

**Comment by kasperski95** [comment]
Duplicate of https://github.com/software-mansion/protostar/issues/262
