### ISSUE TITLE
Make protostar work with `cairo-ls` VS Code extension

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#319]

**Comment by kasperski95** [comment]
Or should we create a fork to be able to support custom Protostar decorators.

**Comment by MaksymilianDemitraszek** [comment]
#208

**Comment by kasperski95** [comment]
@MaksymilianDemitraszek 

Did you create a PR for this task?
https://github.com/ericglau/cairo-ls/issues/29
