### ISSUE TITLE
Use data transformer in `deploy_contract`

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#331]

**Comment by MaksymilianDemitraszek** [comment]
We probably want to pospone it to after we merge #324

**Comment by kasperski95** [comment]
Data transformer shouldn't change because of 0.9.0. Why do you want to postpone this task?

**Comment by MaksymilianDemitraszek** [comment]
This task should support data transformer in:
- `mock_call`
- `deploy_contract` in tests
- `deploy`

It probably shouldn't change in `0.9` but both task will touch many places in the codebase which may cause a lot of merge conflicts. 

Also deploy is still untested for `0.9` so we are not sure if it doesn't change.

Pospone is maybe too strong word, I think it would be better to just do it after we merge #324 (or on the top of it), which is mostly done.

**Comment by kasperski95** [comment]
I need to split this task.

**Comment by MaksymilianDemitraszek** [comment]
Just remember to:
- include all changes into add release
- or add warning in docs if transformation is not supported for a specific cheatcode
