### ISSUE TITLE
`prepare_deploy_contract` cheatcode

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#352]
Proposal:
```
func ():
%{
  dep = Contract("./contract.cairo",  [1,2,3])
  start_prank(123, target=dep.contract_address)
  dep.deploy()
%}
end
```
Would work also for `mock_call` and any targeted cheatcode. 

We could in the future deprecate `deploy_contract`, and instead use:
```
%{
  dep = Contract("./contract.cairo",  [1,2,3]).deploy()
%}
```

Interface
```
class Contract:
__init__(path, calldata): ...

def deploy(self) -> Contract: ...
```

**Comment by kasperski95** [comment]
```
%{
  c = Contract('./contract.cairo')
  start_prank(123, target=c)
  c.deploy([1,2,3])
}
```

**Comment by MaksymilianDemitraszek** [comment]
Looks better 😄

**Comment by kasperski95** [comment]
We can create a mapping tmp_address -> actual_address, which could be updated by Contract::deploy just before deploying a contract.

**Comment by kasperski95** [comment]
If we provide the constructor data at the very beginning we need to detect if the contracts are deployed in the expected order. I still believe we should use the tmp_address -> actual_address mapping.

```python
%{
  c1 = Contract("./contract.cairo",  [1,2,3])
  c2 = Contract("./contract.cairo",  [1,2,3])
  start_prank(123, target=c1.contract_address)
  c2.deploy()
  c1.deploy()
%}
```

**Comment by MaksymilianDemitraszek** [comment]
@kasperski95 Why?

**Comment by kasperski95** [comment]
NVM, I thought generation of contract address depends on the Starknet's state.

**Comment by MaksymilianDemitraszek** [comment]
#379
