### ISSUE TITLE
Support more types in `context`, but do not allow to store heavy to copy objects

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#371]
A user may want to store uint256 dict or a tuple.

**Comment by MaksymilianDemitraszek** [comment]
I think we should make scope of accessible types equivalent to types supported by starknet py transformer

**Comment by kasperski95** [comment]
I think we should allow storing anything and create some blacklist.

**Comment by MaksymilianDemitraszek** [comment]
Disagreed, what you would blacklist?

**Comment by kasperski95** [comment]
I'd try to detect and prevent from storing `DeployedContracts`. The blacklist would grow if necessary.

**Comment by MaksymilianDemitraszek** [comment]
Hmm, new version of deployedContract will solve this so it won't be that easy for user to shoot himself in foot. We probably can whitlelist everything.  We can't prevent user from storing there anything he wants, we jsut should make it not easy to break.

**Comment by MaksymilianDemitraszek** [comment]
We should deprecate old `deploy_contract` first though

**Comment by MaksymilianDemitraszek** [comment]
Updated description:
- after #375 
- remove type check from contex
