### ISSUE TITLE
Unable to start protostar on nixos

### ISSUE THREAD

**Issue by Th0rgal** [software-mansion/protostar#374]
## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `0.2.3`  |
| Cairo-lang | `not applicable` |
| Git        | `2.33.3`        |

## Current Behavior
I get
```protostar: command not found``` 
after typing ``protostar in terminal``

When I go within ``~/.protostar/dist/protostar`` and type ``ls -l | grep protostar``, I get:
```-rwxr-xr-x 1 thomas users 11235152 Jun  8 13:46 protostar```
But in the same directory when I ctype ``./protostar`` I get:
```zsh: no such file or directory: ./protostar``` 

## Expected Behavior
This should start protostar

## Steps to Reproduce

1. Install nixos on x86 computer
2. Install protostar using ``curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash
``
3. Try to start protostar

## Possible Solution

Release a protostar python package and provide a list of the required libs instead of a binary.

**Comment by Th0rgal** [comment]
> https://docs.swmansion.com/protostar/docs/tutorials/installation Section: How to build Protostar from source code

Thank you, I was able to build protostar wheel and install it but how should I use it? Typing ``protostar`` or ``python -m protostar`` doesn't work.

**Comment by kasperski95** [comment]
`python ./binary_entrypoint ...`
or
1. `poe build`
2. `./dist/protostar/protostar ...`

**Comment by MaksymilianDemitraszek** [comment]
I assume it's solved, closing

**Comment by Th0rgal** [comment]
> 



> `python ./binary_entrypoint ...` or
> 
> 1. `poe build`
> 2. `./dist/protostar/protostar ...`

Hey thank you but I didn't get a protostar folder.

```
❯ poetry build
Building protostar (0.2.3)
  - Building sdist
  - Built protostar-0.2.3.tar.gz
  - Building wheel
  - Built protostar-0.2.3-py3-none-any.whl
❯ ls -l dist
total 168
-rw-r--r-- 1 thomas users 104420 Jun 26 09:50 protostar-0.2.3-py3-none-any.whl
-rw-r--r-- 1 thomas users  61848 Jun 26 09:50 protostar-0.2.3.tar.gz
```

I extracted the .tar.gz file but I could't start this file. ``binary_entrypoint.py`` does work though

**Comment by kasperski95** [comment]
`poe build` != `poetry build` at least in this case
