### ISSUE TITLE
Remove old `deploy_contract` cheatcode

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#375]

**Comment by kasperski95** [comment]
*deprecate

**Comment by MaksymilianDemitraszek** [comment]
Nah, we can remove it, new interface is compatible.

**Comment by kasperski95** [comment]
Did you mean removing old `deploy_contract` code?

```python
"deploy_contract": build_deploy_contract(deployment_manager),
```
Currently, `deploy_contract` is an abstraction over declare, prepare and deploy.

**Comment by MaksymilianDemitraszek** [comment]
#358 I will wait until this one is merged, as it will require using data transformer in the new `deploy_contract` cheatcode

**Comment by MaksymilianDemitraszek** [comment]
@kasperski95 It's probably done, is it?
