### ISSUE TITLE
Allow to build account contracts

### ISSUE THREAD

**Issue by florian-bellotti** [software-mansion/protostar#399]
Today, when we try to build an account contract, we have this issue:

```shell
> protostar build       
[ERROR] Protostar couldn't compile '<CONTRACT>' contract
Only account contracts may have a function named "__execute__". Use --account_contract flag.
```

How could we pass the `--account_contract` flag ?

**Comment by kasperski95** [comment]
@florian-bellotti 
https://github.com/software-mansion/protostar/releases/tag/v0.2.5-pre-release
