### ISSUE TITLE
Deployment scripts MVP

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#404]
> The way I imagine it - I want to be able to test the system that will be deployed in production.
I argue that the way you deploy the contracts can effect your system, so you want to make sure that your tests are testing the same thing.

**Comment by kasperski95** [comment]
# Research results:
- deploy script → migration script
- similar migration approach to `Truffle`
- new command: `migrate`
- common test/migration cheatcodes:
  - `build` -> trigger building
  - `declare` and `deploy_contract` should accept compiled contracts as input
  - `deploy_declared` — `prepare` cheatcode won't be available in the migration environment
  
### Examples
- `migration/01_migrate.cairo` 
```cairo
%lang starknet

func migrate(args_count: felt, args: felt*):
  %{
      account_address = ids.args[0]
      result = {}
      build()
      result["foo_class_hash"] = declare("./build/foo.json")
  %}
  return ()
end
```

- `migration/01_migrate_test.cairo` 
```cairo
from migration.01_migrate.cairo import migrate

@view
func test_migrate():
    let (local args : felt*) = alloc()
    migrate(0, args)
    %{
        result["foo_class_hash"] 
        # ...
    %}
end

- `protostar migrate --args $(echo $ACCOUNT_CONTRACT)`

```

**Comment by kasperski95** [comment]
```cairo
func up(a,b,c):
  
end
```

`protostar migrate-up --inputs 1 2 3`

```toml
[protostar.migrate-up]
inputs=[1,2,3]
```

**Comment by mkaput** [comment]
> Protostar commands must be one level deep to generate CLI docs so:
> 
> protostar migrate-up
> protostar migrate-down

Hmm, with this constraint I think `protostar migrate` as you originally proposed was fine 😄 I have seen somewhere following design `protostar migrate --down` so maybe we could reserve this one for us...

I do wonder though if we will reach a need for down migrations now 🤔 

> I thought about this, but I'd have to preprocess the migration script everytime before argparse is configured.

I think the implementation would have to escape limitations of `argparse` here and do parsing itself. That's why I thought about using a different prefix for argument names (`@x` instead of `--x`). From `argparse` point of view, the migrate command would accept arbitrary amount of extra string parameters.

> Also, migration args couldn't be defined in the protostar.toml, unless Protostar combines CLI's unknown-args and protostar.toml::[protostar.migrate] into one dict and passes it as a hint. All arguments would be a string though.

Do we need to support this case, though? I cannot imagine benefits, as that would gradually litter `protostar.toml`.

**Comment by kasperski95** [comment]
> I think the implementation would have to escape limitations of argparse here and do parsing itself. That's why I thought about using a different prefix for argument names (@x instead of --x). From argparse point of view, the migrate command would accept arbitrary amount of extra string parameters.

For the time being, I'll make it consistent with the `inputs` argument or the `deploy` command. In the future, we can think about the custom parses for both of these commands.

> Do we need to support this case, though? I cannot imagine benefits, as that would gradually litter protostar.toml.

Somebody may try to run `migrate` in the devnet network over and over. Defining `inputs` in the `protostar.toml` would avoid providing them manually every time. 

It's also about consistency. We try to make every argument configurable from the `protostar.toml`. Actually, it shouldn't be a problem:
```toml
[protostar.migrate]
inputs = "@x 1 @y 2"
```

**Comment by kasperski95** [comment]
Blocked by https://github.com/software-mansion/protostar/issues/415

**Comment by kasperski95** [comment]
Blocked by #439
