### ISSUE TITLE
Allow disabling progress bar

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#411]

**Comment by MaksymilianDemitraszek** [comment]
Do we have to include this one in this release?

**Comment by kasperski95** [comment]
It's a small task and an intern joins our team if I'm not mistaken. Progress bar clutters the output in the CI and `print` causes the following issue:

![unknown](https://user-images.githubusercontent.com/9629577/176925025-9367a6b5-d0f8-476a-bdcb-2a514f608545.png)

**Comment by mkaput** [comment]
I think many CLI tools inspect environment variables to disable interactivity. I guess this env var is named `TERM` but I may be mistaken.

**Comment by MaksymilianDemitraszek** [comment]
related task https://github.com/software-mansion/protostar/issues/110


But is interactivity considered any cli output or requesting user inputs @mkaput ? Because this taks is only related to cli output.

**Comment by mkaput** [comment]
IMHO progress bar should only be shown if user input is possible in the terminal.
