### ISSUE TITLE
Allow for setting sys.path in protostar.toml

### ISSUE THREAD

**Issue by milancermak** [software-mansion/protostar#422]
As mentioned [in discord](https://canary.discord.com/channels/793094838509764618/964116575387021413/994337657842839653), I'd like to import my own python functions in hints. This is currently not straightforward because I have to manipulate `sys.path`.

What I've currently settled on is to do the path manipulation in `__setup__` and imports in the hints themselves.

```
@external
func __setup__():
    %{
        import os, sys
        sys.path.append(os.path.abspath(os.path.dirname(".")))
    %}

    return ()
end

@external
func test_foo():
    # ...
    
    local expected
    %{
        from tests.my_module.utils import my_func
        ids.expected = my_func(42)
    }%
    # ...
end
```

It works, but could be made better.

One suggestion is to automatically have the directory in which the `test_foo.cairo` file is located placed in `sys.path` so that I can have `utils.py` sitting in the dir structure right next to my test files. Another thing that would be beneficial is to have a config setting in `protostar.toml` where I could list paths that I want to have added to `sys.path` for each test file so that I don't have to manipulate the path inside `__setup__`.

**Comment by Arcticae** [comment]
@milancermak we synchronize the sys.path with project's cairo-path, which we mention here:
https://docs.swmansion.com/protostar/docs/tutorials/deploying/cli#2-using-a-custom-signer-class
Does this make things easier for you?

**Comment by Arcticae** [comment]
Also a note, when adding this enhancement we should also consider:
- Adding `PYTHONPATH` to `sys.path`
- synchronize `cairo-path` parameter from the command line prompt with the `sys.path` (it doesn't seem to happen right now)

**Comment by milancermak** [comment]
Yes, using `cairo-path` would work for my original issue. It's not obvious that it would work for Python as well due to the name, but that's just a documentation issue I suppose.

**Comment by Arcticae** [comment]
@milancermak you should be able to execute your original code in the newer protostar versions, since the root of the project is added to `cairo-path`. This might not work with additional CLI's `--cairo-path` just yet, i'm going to start doing some work on that.

**Comment by Arcticae** [comment]
This should be possible right now, since pythonpath is being synced with cairo-path
