### ISSUE TITLE
[BUG] Cairo path error

### ISSUE THREAD

**Issue by 08351ty** [software-mansion/protostar#433]
i'm getting this error where i have OZ protostar dependencies within my repo but my import functions are giving errors:
Could not find module 'openzeppelin.account.library'. Searched in the following paths:
```
/home/vscode/.protostar/dist/protostar/cairo/openzeppelin/account/library.cairo
/workspaces/realms-contracts/openzeppelin/account/library.cairo
/workspaces/realms-contracts/lib/openzeppelin/account/library.cairo
/workspaces/realms-contracts/lib/cairo_contracts/openzeppelin/account/library.cairo
/workspaces/realms-contracts/lib/cairo_math_64x61/openzeppelin/account/library.cairo
/workspaces/realms-contracts/openzeppelin/account/library.cairo
/home/vscode/.protostar/dist/protostar/openzeppelin/account/library.cairo
from openzeppelin.account.library import Account, AccountCallArray
```
but the correct path should be:
`./lib/cairo_contracts/**src**/openzeppelin/account/library.cairo`

basically missing the /src/ folder. My protostar.toml files are as such:
```
["protostar.build"]
cairo-path = ["./lib/cairo_contracts/src"]```
```
so not sure why it's missing /src file 

## Protostar version

0.2.5

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `PROTOSTAR_VERSION`  |
| Cairo-lang | `CAIRO_LANG_VERSION` |
| Git        | `GIT_VERSION`        |

## Current Behavior

fails to find OZ lib, can't find the correct path.

## Expected Behavior

Should correctly get the OZ libs

## Steps to Reproduce

1. Fork this and run using dev container: https://github.com/BibliothecaForAdventurers/realms-contracts
2. Run "protostar test tests/protostar/nft_marketplace/test_bibliotheca_marketplace.cairo"

**Comment by kasperski95** [comment]
`protostar.toml` configures the `build` command.

`protostar.toml`
```diff
- ["protostar.build"]
+ ["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src"]

```
