### ISSUE TITLE
[BUG] Class with hash 0x... is not declared

### ISSUE THREAD

**Issue by 08351ty** [software-mansion/protostar#444]
Calling 
```IERC20.transferFrom(currency, caller, trade.poster, Uint256(base_seller_receives, 0))```
shows an error:

```starkware.starkware_utils.error_handling.StarkException: (500, {'code': <StarknetErrorCode.UNDECLARED_CLASS: 42>, 'message': 'Class with hash 0x631efd82d6a2e94ea8d7204e700851adfc14c908d706a5ebd631980f6716c50 is not declared.'})```

## Protostar version

0.2.5

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `PROTOSTAR_VERSION`  |
| Cairo-lang | `CAIRO_LANG_VERSION` |
| Git        | `GIT_VERSION`        |

## Expected Behavior

Getting this StarkException:
```starkware.starkware_utils.error_handling.StarkException: (500, {'code': <StarknetErrorCode.UNDECLARED_CLASS: 42>, 'message': 'Class with hash 0x631efd82d6a2e94ea8d7204e700851adfc14c908d706a5ebd631980f6716c50 is not declared.'})```

## Steps to Reproduce

1. Fork realms repo: https://github.com/BibliothecaForAdventurers/realms-contracts
2. Run: protostar test tests/protostar/nft_marketplace/test_bibliotheca_marketplace.cairo::test_open_trade_and_execute

**Comment by MaksymilianDemitraszek** [comment]
Probably not relevant anymore
