### ISSUE TITLE
Add support for dumping cairo structures to dicts

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#469]
We need a simple way to dump local cairo structure as python dict or list.
I propose a cheatcode `dump` (name TBD)
```
struct VoterInfo:
    member a : felt
    member b: felt
end

func:
alloc_locals
local value: VoterInfo
assert value.a = 1
assert value.b = 2
%{
    print(dump(ids.value))
    print(dump(ids.value, raw=True)
%}
end
``` 
Result
```
{"a": 1, "b": 2}
[1,2]
```

We need to go recursively down the `VmConstsReference`, `src/starkware/cairo/lang/vm/vm_consts.py` and fetch the data directly from memory bus.

**Comment by milancermak** [comment]
The testing framework in `cairo-lang` has this cool feature where when I [deploy a contract](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/testing/contract.py#L37), I can create any [instance of a struct](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/testing/contract_utils.py#L19) just as if it was an attribute of the contract.

Taking the example from above, in a python test, I could do:

```python
from starkware.starknet.testing.starknet import Starknet, StarknetContract

starknet = await Starknet.empty()
contract = await starknet.deploy("voter_contract.cairo")
voter_info = contract.VoterInfo("value_for_a", "value_for_b")
assert voter_info.a = "value_for_a"
```

Would it be possible to `dump` into a struct like this? Alternatively a `namedtuple` for a struct would work as well - they are super useful and easy to work with, so something along the lines of:

```
# in a hint
from collections import namedtuple

VoterInfo = namedtuple("VoterInfo", "a b")
assert dump(ids.value, raw=True) = VoterInfo(1, 2) # this would work if the repr was a tuple, not a list
```

**Comment by Radinyn** [comment]
@milancermak
I'll definitely look into this.

**Comment by MaksymilianDemitraszek** [comment]
https://github.com/software-mansion/protostar/pull/484#issuecomment-1188997636
