### ISSUE TITLE
Run heavy tests only on merge to master

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#474]
As a Protostar dev, I don't want GitHub Action to test upgrading every time I push the code, so that the job runs faster and the release download stats are less polluted.

e.g. e2e:
- upgrading
- package management

**Comment by MaksymilianDemitraszek** [comment]
What is the status of this task, should we close it?

**Comment by kasperski95** [comment]
Currently, we run tests in parallel. It's not too bad. Closing.
