### ISSUE TITLE
Improve output when run in CI

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#487]
![Image](https://user-images.githubusercontent.com/9629577/179474162-0275ec30-cf54-445a-b443-b7ab3504e04f.png)

- disable activity indicator
- remove `--no-progress-bar`

**Comment by mkaput** [comment]
I am 99% sure this flag is not needed and Protostar could be able to infer that TTY is not interactive from running environment. Does TQDM properly degrade in CI?
