### ISSUE TITLE
Refine testing docs

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#492]
The current document is too large.

Move cheatcodes documentation to a separate document.

The main document should have two main chapters:
- essentials (20%)
- not-essentials... (80%)

The learning curve should be flat.

**Comment by MaksymilianDemitraszek** [comment]
Is this done?

**Comment by mkaput** [comment]
I think we can assume yes. We didn't edit the text itself, only chopped it into more bearable pieces
