### ISSUE TITLE
Expose `deploy` commands as Python deployments APIs

### ISSUE THREAD

**Issue by 0xSidius** [software-mansion/protostar#503]
Currently Protostar only supports deployment operations through a CLI-only wrapper that resembles starknet-cli own commands. This is not adequate for larger scale projects or generally more complex deployment workflows that need to be written as code (Python). 

To enable and better support complex deployment scenarios, Protostar should expose and document all the relevant `deploy` commands as Python APIs as well.

**Comment by MaksymilianDemitraszek** [comment]
We want to allow users to write testable cairo migration scripts using hints, you can contribute to discussion in the mentioned task, as we are currently implementing it. 

I think it addresses your request so I am closing this one.
