### ISSUE TITLE
Negative fuzz counts if test fails

### ISSUE THREAD

**Issue by mkaput** [software-mansion/protostar#553]
Failing test reports negative count of fuzz simplification runs:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/3450050/182187665-a1f6779b-6979-4c60-8e65-c5e382fb7bcc.png">

To reproduce, simply `raise ProtostarException` from a hint in a fuzz test.

**Comment by kasperski95** [comment]
🤦
