### ISSUE TITLE
[BUG] - protostar commands are very slow

### ISSUE THREAD

**Issue by ImmanuelSegol** [software-mansion/protostar#568]
## Protostar version
Protostar version: 0.3.0
Cairo-lang version: ^0.9.1

OS - 
macOS Monterey version 12.4

## Current Behavior
When running commands such as, `protostar -v`. I experience a lag of 1-5 seconds.

## Expected Behavior
The CLI app should be responsive.

## Steps to Reproduce
1. Follow instructions https://docs.swmansion.com/protostar/docs/tutorials/installation#linux-and-mac
2. run `protostar -v`

## Possible Solution
I'm not sure I didn't look at the code, I'm just reporting the issue.

**Comment by MaksymilianDemitraszek** [comment]
Thank you for reporting the issue! I believe we have some actionable steps on our roadmap to improve it!
