### ISSUE TITLE
protostar format

### ISSUE THREAD

**Issue by Bal7hazar** [software-mansion/protostar#569]
As a StarkNet smart contract developer, I would like protostar to provide a ~linter~ code formatter (using `cairo-format` under the hood) so that for casual developers it's no longer mandatory to install a python environment to get a clean code.

Note: ` -i`  and ` -c`  options should be kept as they are in the protostar CLI (since both are usefull).

**Comment by mkaput** [comment]
`cairo-format` is not a linter but code formatter. I suggest renaming the feature to `protostar fmt`. Wdyt? @kasperski95 @MaksymilianDemitraszek

**Comment by mkaput** [comment]
Also, I think that the write mode (`-i` switch) should be on by default, with the `check` mode (`-c`) being an option. I don't see an use case for a report to stdout mode in Protostar itself.

**Comment by Bal7hazar** [comment]
> `cairo-format` is not a linter but code formatter. I suggest renaming the feature to `protostar fmt` and let it behave the same as `cargo fmt` or `mix format`. Wdyt? @kasperski95 @MaksymilianDemitraszek

I agree, imho `protostar format` suits better than `protostar fmt` since all other commands are entire names (except if you schedule to provide new short commands of course).

**Comment by kasperski95** [comment]
> protostar fmt

I'd use the full name — `protostar format`. If we want to save keystrokes, we should consider renaming `protostar` to `proto` e.g. `proto format`.

> Also, I think that the write mode (-i switch) should be on by default, with the check mode (-c) being an option. I don't see an use case for a report to stdout mode in Protostar itself.

I'd go with the safe by default approach. You can always change the behavior in the `protostar.toml`. By default, all flags in Protostar are off/false, so we should consider changing flags name.

Also Protostar format shouldn't fail if a file doesn't compile.

**Comment by mkaput** [comment]
Yeah, `protostar format` is better here.

**Comment by mkaput** [comment]
> I'd go with the safe by default approach. You can always change the behavior in the `protostar.toml`. By default, all flags in Protostar are off/false, so we should consider changing flag names.

What do you mean by `safe by default`? Not overriding files? Then what's the point of formatting the whole project?

> Also Protostar format shouldn't fail if a file doesn't compile.

I think it should fail for not compilable files, but properly continue with valid ones. `mix format` works that way. `cargo fmt` even refuses to override anything, but Cairo does not has such strong coupling of parsing and module loading as Rust has. Both tools report compilation errors. I don't know how other similar tools behave, but I bet it's similar.

![image](https://user-images.githubusercontent.com/3450050/183842045-37df01a6-64fd-4e5e-b4dc-c5d4bd084923.png)

**Comment by kasperski95** [comment]
> What do you mean by safe by default? Not overriding files? Then what's the point of formatting the whole project?

Checking if the project is correctly formatted (CI check).
`protostar format --fix` could overwrite files.

Anyway, we should do a research and make it work similarly to other known formatters.
https://en.wikipedia.org/wiki/Principle_of_least_astonishment

> I think it should fail for not compilable files, but properly continue with valid ones.

+1

We need to keep in mind that users could want to use the formatter with VS Code.
![Screenshot 2022-08-10 at 09 57 24](https://user-images.githubusercontent.com/9629577/183847134-8952bbb5-b120-4155-9f80-9c0768e21eb6.png)

**Comment by mkaput** [comment]
> Checking if the project is correctly formatted (CI check). `protostar format --fix` could overwrite files.
> 
> Anyway, we should do a research and make it work similarly to other known formatters. https://en.wikipedia.org/wiki/Principle_of_least_astonishment

CI checks == `protostar format --check`

Formatting project == `protostar format`


> +1
> 
> We need to keep in mind that users could want to use the formatter with VS Code. ![Screenshot 2022-08-10 at 09 57 24](https://user-images.githubusercontent.com/9629577/183847134-8952bbb5-b120-4155-9f80-9c0768e21eb6.png)

IDEs should call `cairo-format` directly if they want to format a file. `protostar format` should just be a wrapper that runs over whole project from CLI.

**Comment by kasperski95** [comment]
> IDEs should call cairo-format directly if they want to format a file

Users would have to set up the environment. Maybe we should create a Protostar extension for VS Code. 

> As a StarkNet smart contract developer, I would like protostar to provide a linter code formatter (using cairo-format under the hood) so that **for casual developers it's no longer mandatory to install a python environment to get a clean code.**

**Comment by mkaput** [comment]
> > IDEs should call cairo-format directly if they want to format a file
> 
> Users would have to set up the environment. Maybe we should create a Protostar extension for VS Code.
> 
> > As a StarkNet smart contract developer, I would like protostar to provide a linter code formatter (using cairo-format under the hood) so that **for casual developers it's no longer mandatory to install a python environment to get a clean code.**

Ah forgot about that.

For usage in editors for files, I think indeed that interface of `cairo-format` is better. Maybe we could offer two commands? `protostar format` for project formatting and CI and `protostar cairo-format [-i] [-c] FILE...` as just a wrapper of `cairo-format` for usage in editors?

From code editor point of view, it is also important to support stdin→stdout formatting

**Comment by kasperski95** [comment]
Or a user could run custom script `protostar format` on save.

https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave
