### ISSUE TITLE
Capability to specify the version to install/upgrade

### ISSUE THREAD

**Issue by ca11ab1e** [software-mansion/protostar#570]
As a StarkNet smart contract developer, I want to **pin the exact Protostar version to install, or update to**, so that **the devenv setup is reproductible, and kept stable**.

For instance, installing Protostar in our CI will always install the latest version available, and our code wasn't migrated to Cairo 0.9.1 at the time, so all our tests start failing.

It would be very powerful to be able to specify the desired version at install, and upgrade, by looking at the expected version from the configuration file.

WDYT?

**Comment by kasperski95** [comment]
Related https://github.com/software-mansion/protostar/issues/570
