### ISSUE TITLE
Report testing seed even if Protostar crashed

### ISSUE THREAD

**Issue by mkaput** [software-mansion/protostar#592]
As happened for the bug reporter in #590, Protostar has crashed due to unexpected exception, and it didn't report the testing seed and other statistics, thus it's hard for us to reproduce the bug locally.

User should be able to see Testing Summary even if Protostar crashed.

**Comment by mkaput** [comment]
@kasperski95 assigning to you because you are working on #584 and this will be related.

**Comment by mkaput** [comment]
I also think we should report the seed (and the summary in general) in integration tests logs.

**Comment by mkaput** [comment]
> > I also think we should report the seed (and the summary in general) in integration tests logs.
> 
> 
> 
> Why would that be needed?

Because if an integration test with arbitrary seed crashes, I won't also know the value of the seed :)

**Comment by kasperski95** [comment]
Partially blocked by https://github.com/software-mansion/protostar/issues/544

**Comment by mkaput** [comment]
@kasperski95 I think we can cancel this? Because we concluded that the user simply didn't collaborate as we thought in the reference issue.

**Comment by kasperski95** [comment]
Yep, let's cancel this. It's not super important.
