### ISSUE TITLE
Protostar seems to be incompatible with new M2 chip

### ISSUE THREAD

**Issue by Th0rgal** [software-mansion/protostar#605]
Hello there. I just installed protostar on a new M2 macbook air. When trying to run ``protostar`` I got this message:
```
zsh: bad CPU type in executable: protostar
```

## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `3.0.0`  |
| Cairo-lang | `not sure` |
| Git        | `2.36.0`        |

## Current Behavior

```
zsh: bad CPU type in executable: protostar
```

## Expected Behavior

It should start protostar

## Steps to Reproduce

1. Install protostar on a M2 mac computer
2. profits

**Comment by MaksymilianDemitraszek** [comment]
We may look on it in the future(we have no m2 machine to test it though). For now i suggest building it by yourself based on https://github.com/software-mansion/protostar#development

**Comment by Th0rgal** [comment]
> We may look on it in the future(we have no m2 machine to test it though). For now i suggest building it by yourself based on https://github.com/software-mansion/protostar#development
> 
> 
> 
> 

Thank you, I'm available if you need me to try things. I tried to build it but couldn't get the poe command. Where does it come from?

**Comment by Th0rgal** [comment]
When building it by myself and calling it:
- init works
- build works
- test doesn't work

When performing the tests directly from source code in a newly created protostar project via ``python ~/workspace/protostar/binary_entrypoint.py test``, I got this error:
https://gist.github.com/Th0rgal/03c6902c65fe5afbbe2010792145d2ec

**Comment by Th0rgal** [comment]
> When building it by myself and calling it:
> 
> * init works
> * build works
> * test doesn't work
> 
> When performing the tests directly from source code in a newly created protostar project via `python ~/workspace/protostar/binary_entrypoint.py test`, I got this error: https://gist.github.com/Th0rgal/03c6902c65fe5afbbe2010792145d2ec

I've been able to fix the tests issue by replacing ``multiprocessing`` from standardlib by ``multiprocess``, a fork which uses the dill serializer instead of pickle (it's the only difference). You can find more info about it here: https://pypi.org/project/multiprocess/

Testing by calling binary_entrypoint was fixed, but when I tried to build protostar via ``poe build``, the generated dist folder didn't contain multiprocess and I kept an issue with "multiprocessing" so I probably didn't do it correctly, I would really appreciate if you could show me how to correctly build it, or even replace multiprocessing by multiprocess in the final version.

**Comment by kasperski95** [comment]
Maks is not available this week. `poe build` should've work. Maybe some tweaking needs to be done in the `protostar.spec`? Did you replace all multiprocessing imports?

**Comment by Th0rgal** [comment]
> Maks is not available this week. `poe build` should've work. Maybe some tweaking needs to be done in the `protostar.spec`? Did you replace all multiprocessing imports?

Alright. Yep I replaced all multiprocessing imports in the folder. I am not sure what I should tweak in protostar.spec.

**Comment by kasperski95** [comment]
My hypothesis: the dist folder is outdated because e.g. the build failed, but that information was lost in logs

(TBH, I can't debug this problem without access to M2.)

**Comment by Th0rgal** [comment]
> My hypothesis: the dist folder is outdated because e.g. the build failed, but that information was lost in logs
> 
> (TBH, I can't debug this problem without access to M2.)

If you want to try things on M2 we can have a call and I could share you my terminal by ssh.

**Comment by kasperski95** [comment]
Thanks, the problem with the dist folder is not obvious. It can take some time, so I'd rather work on it locally.
I've just requested M2, so I'll take a look at this issue soon.

**Comment by kasperski95** [comment]
`poe build` works on M2:

[protostar--0-3-3-mac-arm--prerelease.zip](https://github.com/software-mansion/protostar/files/9395720/protostar--0-3-3-mac-arm--prerelease.zip)

**Comment by Th0rgal** [comment]
That works perfectly, thank you so much sir.

**Comment by kasperski95** [comment]
To fix `zsh: bad CPU type in executable: protostar` install Rosetta:
`softwareupdate --install-rosetta`
