### ISSUE TITLE
Add missing (test) assertions

### ISSUE THREAD

**Issue by Arcticae** [software-mansion/protostar#61]
Compared to Foundry

**Comment by kasperski95** [comment]
I think there's no point of adding assertions.

| Foundry (ds-test)*                                                          | starkware.cairo.common.math |
| ---------------------------------------------------------------- | --------------------------- |
| assertTrue                                                       | assert_not_zero             |
| assertEq                                                         | assert_not_equal            |
| assertEqDecimal                                                  | -                           |
| assertGt                                                         | -                           |
| assertGe                                                         | -                           |
| assertLt                                                         | assert_lt                   |
| -                                                                | assert_lt_felt              |
| assertLe                                                         | assert_le                   |
| -                                                                | assert_le_felt              |
| -                                                                | assert_nn                   |
| -                                                                | assert_nn_le                |
| -                                                                | assert_250_bit              |
| -                                                                | assert_in_range             |
| -                                                                | static_assert               |

*Each assert has a corresponding variant that accepts an error message.

**Comment by kasperski95** [comment]
Make naming and importing consistent.
