### ISSUE TITLE
Add `--watch` flag to test command

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#612]
As a TDD practitioner, I want to see if tests pass or fail without manually executing the Protostar.

**Comment by mkaput** [comment]
Example approach for this taken by `mix test`: https://hexdocs.pm/mix/1.14.0-rc.1/Mix.Tasks.Test.html#module-file-system-watchers

**Comment by MaksymilianDemitraszek** [comment]
🐌
