### ISSUE TITLE
Protostar deployment issues

### ISSUE THREAD

**Issue by Darlington02** [software-mansion/protostar#636]
## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `0.3.1`  |
| Cairo-lang | `0.9.1` |
| Git        | `2.37.1`        |

## Current Behavior

after updating my protostar to 0.3.1, my deployed contracts to alpha-goerli testnet using the protostar deploy command no longer shows up on Voyager

## Expected Behavior

Right before the update, after deploying my contracts, it takes about few minutes to show up on voyager, but its over 12 hours now, and my deployments are not showing up yet. Confused as to if its an issue with Voyager or Protostar

## Steps to Reproduce

1. run the protostar deploy command
```protostar deploy ./build/main_ex1.json --network alpha-goerli --inputs 297732878896 1162824514 5 0 292571036158309430053914102603121793915440959967340882752864723702445055560 620000000000000000000 0```

2. copy the link to the deployed link on voyager to check if it shows up.

**Comment by tdelabro** [comment]
Same problem when trying to deploy on a local dev-net. Use to be done in a few seconds, still waiting for it to happen.

**Comment by Radinyn** [comment]
Hello @Darlington02, @tdelabro

Does this issue still occur?
If yes can you provide more details? We are currently unable to replicate this behaviour.

**Comment by Darlington02** [comment]
Yes it still ver much occurs @Radinyn 

i am trying to deploy a simple ERC20 contract using openzeppelin's library, contract can be found here.
https://github.com/Darlington02/starknet-edu-ERC20/blob/master/src/ERC20_ex1.cairo

here's how my constructor looks
```@constructor
func constructor{
        syscall_ptr : felt*,
        pedersen_ptr : HashBuiltin*,
        range_check_ptr
    }(name: felt, symbol: felt, decimals: felt, totalSupply: Uint256, owner: felt):
    alloc_locals
    # initialize an owner
    Ownable.initializer(owner)

    ERC20.initializer(name, symbol, decimals)
    ERC20._mint(owner, totalSupply)
    return ()
end
```

so during the deployment, i provide input arguments of name(in felt), symbols (in felt), decimals (in felt), totalSupply and owner(in felt). my deployment command looks like this

```
protostar -p testnet deploy ./build/main_ex1.json --inputs 297732878896 1162824514 18 0 620000000000000000000 292571036158309430053914102603121793915440959967340882752864723702445055560
```

when i run the command, it throws no error and says successfully deployed

```
18:03:47 [INFO] Deploy transaction was sent.
Contract address: 0x01684b594a8b9c8c6341d562d9a0314d28867def3a2bb5d0af1ffb1d029e586f
Transaction hash: 1137941189590418255238645330081822482805330561623597172601516111667613133063

https://goerli.voyager.online/contract/0x01684b594a8b9c8c6341d562d9a0314d28867def3a2bb5d0af1ffb1d029e586f
```

but when i open the contract, on voyager, it throws a 404 contract not found, even after waiting for long hours.

P.S i noticed, i'm able to deploy simple contracts with no constructor, like the boiler contract that comes with protostar, and view them on voyager,  but having issues with contracts that accept constructor arguments.

Lastly, im new to cairo, and might probably be doing something wrong, but i think if my deployment command was wrong, protostar should have thrown an error or something.

**Comment by Radinyn** [comment]
Thank you @Darlington02,
We are still working on reproducing this behaviour.
Could you check what happens when you run it with the --wait-for-acceptance flag?
Also, what OS are you using?

**Comment by Darlington02** [comment]
Wil try that now. 
I use macos, m1 chip

**Comment by Darlington02** [comment]
Hi @Radinyn 

Finally found a solution to the deployment issues. turns out i was trying to assign a felt to a Uint256 in the constructor.

But what i'm curious about is why didn't protostar throw an error of some sort? but rather deployed a non-existent contract?

I hope this can be fixed in future versions🙏🏽

Thanks for your assistance.
