### ISSUE TITLE
Breaking change in patch 0.3.1

### ISSUE THREAD

**Issue by tdelabro** [software-mansion/protostar#637]
Up until 0.3.1 protostar `deploy` accepted its `inputs` argument as string
`--inputs 0x175666e92f540a19eb24fa299ce04c23f3b75cb2d2332e3ff2021bf6d615fa5` was valid and was used all over our CI.

In 0.3.1 `inputs` is required to be of type `integer`.

It's a breaking change that breaks our CI, in a patch release.

**Comment by tdelabro** [comment]
https://semver.org/
```
Given a version number MAJOR.MINOR.PATCH, increment the:

    MAJOR version when you make incompatible API changes
    MINOR version when you add functionality in a backwards compatible manner
    PATCH version when you make backwards compatible bug fixes
```

**Comment by mkaput** [comment]
Hey @tdelabro, the change in the behaviour that you have observed was actually a bug fix from Protostar perspective. Until 0.3.1 we accepted arbitrary strings in CLI and the fact that the `0x` syntax worked was just a coincidence.

Nonetheless, your usage case makes sense, and we plan to release version 0.3.2 soon that will properly handle hex values.

**Comment by mkaput** [comment]
https://github.com/software-mansion/protostar/releases/tag/v0.3.2
