### ISSUE TITLE
install.sh script should not allways install the last version of protostar, regardless of the specified branch

### ISSUE THREAD

**Issue by tdelabro** [software-mansion/protostar#638]
As a StarkNet smart contract developer, I want to install a past version of protostar.
The `install.sh` script always uses the latest release and version, regardless of the branch we are using in the curl command.

`curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash`
and
`curl -L https://raw.githubusercontent.com/software-mansion/protostar/v0.3.0/install.sh | bash`
both resolve to `v0.3.1`.

This is highly counterintuitive and should not be the behavior.

**Comment by kasperski95** [comment]
Related https://github.com/software-mansion/protostar/issues/570

**Comment by kasperski95** [comment]
Reopening. https://github.com/software-mansion/protostar/issues/570 should allow specifying a specific version from the Protostar CLI.
