### ISSUE TITLE
Minor breaking change after the 0.3.1 release

### ISSUE THREAD

**Issue by Bal7hazar** [software-mansion/protostar#644]
## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `0.3.1^`  |
| Cairo-lang | `0.9.1` |
| Git        | `2.34.1`        |

## Current Behavior
After a successful deployment, the ouput of the tx hash is now a felt.
It is not a major issue but since starknet API `https://alpha4.starknet.io/feeder_gateway/get_transaction_status?transactionHash=` expects a hex, it is less conveniant.

```
Deploy transaction was sent.
Contract address: 0x02c4672468cd6116ae2d8dc07b8d12e2561593e392fa2e693ac4b8576ecaab20
Transaction hash: 3379530798764605818090729322813257897802304273379266993039341877985495062261
```

## Expected Behavior
In previous versions it was a hex (note I didn't test to install a previous version, but some of our scripts does not work anyone due to this)

```
Deploy transaction was sent.
Contract address: 0x02c4672468cd6116ae2d8dc07b8d12e2561593e392fa2e693ac4b8576ecaab20
Transaction hash: 0x778BF24408D10F7262177110CADB96F3CE6E5556D9BB4A8BBBC807D76D196F5
```

## Steps to Reproduce
Deploy a contract.

## Possible Solution
I just had to add a `felt_to_hex` parser to fix it locally.

**Comment by Radinyn** [comment]
Resolved by #651
