### ISSUE TITLE
Report setup hooks and test case timings separately

### ISSUE THREAD

**Issue by mkaput** [software-mansion/protostar#680]
As a StarkNet smart contract developer, I want to see the execution time of the `__setup__` hook (debatable?), `setup_*` function and `test_*` function for each test case separately so that I precisely know which step took which amount of time.

Data is already collected since #671. The missing part is to sensibly surface this to the end user and remove the `total_elapsed` property.

related to #548

**Comment by MaksymilianDemitraszek** [comment]
Should be taken into account in #1537
