### ISSUE TITLE
Multiple calls to expect_revert raises an error

### ISSUE THREAD

**Issue by JorikSchellekens** [software-mansion/protostar#682]
## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `0.3.2`  |
| Cairo-lang | `0.9.1` |
| Git        | `2.37.1`        |

## Current Behavior

Test fails when it should pass

## Expected Behavior

I think that it's reasonable to expect testing scenarios where two non-mutually-exclusive conditions set the expectation that the test should revert.

## Steps to Reproduce

```
%lang starknet

@external
func test_a():
    %{
        expect_revert()
        expect_revert()
    %}
    assert 1 = 0
    return ()
end
```

Output:

```
23:25:23 [INFO] Collected 1 suite, and 1 test case (0.003 s)
[FAIL] tests/test_a.cairo test_a (time=2.11s)
Protostar is already expecting an exception matching the following error:


23:25:26 [INFO] Test suites: 1 failed, 1 total
23:25:26 [INFO] Tests:       1 failed, 1 total
23:25:26 [INFO] Execution time: 4.71 s
```

**Comment by kasperski95** [comment]
> I think that it's reasonable to expect testing scenarios where two non-mutually-exclusive conditions set the expectation that the test should revert.

Protostar doesn't execute a code after receiving a revert error, hence I don't see a use case for the second `expect_revent`. To make this feature justified, we'd have to implement try/catch in `cairo-lang`. That would require deeper integration with `cairo-lang`, which we'd like to avoid due to maintenance reasons.

**Comment by mkaput** [comment]
@kasperski95 maybe we should document this behaviour more thoroughly in our docs? Current behaviour makes sense if we say that we execute each test case wrapped in "virtual" try...except block if you use `expect_revert` cheatcode in the test.

**Comment by kasperski95** [comment]
https://github.com/software-mansion/protostar/issues/686

**Comment by JorikSchellekens** [comment]
@kasperski95  the lack of error message here is also confusing, can you add adding a useful error message to #686?

**Comment by kasperski95** [comment]
https://github.com/software-mansion/protostar/issues/687
https://github.com/software-mansion/protostar/issues/688
