### ISSUE TITLE
Test with a set of inputs / Constrain the fuzzer

### ISSUE THREAD

**Issue by JorikSchellekens** [software-mansion/protostar#683]
I want to be able to test a small number of boundary conditions without needing to write individual functions for each. It would also be nice to constrain the fuzzer in the case that some data type is smaller than a felt - I currently handle this by modding the input in a hint.

```
# arg1: [1, 2, 4, 5]
# arg2: range(0, 100) * 2
func test_edges(arg1 : felt, arg2 : felt):
end
```

**Comment by JorikSchellekens** [comment]
Oh, I see assume could be used for this purpose but it would still be nice to be able to specify inputs exactly.

**Comment by mkaput** [comment]
Hey @JorikSchellekens! I have this feature on track here: #623 (it will be possible to mix parameterized and fuzz approach in single test as both will reuse testing engine) and right now I am slowly making progress in order to get this working. There is high chance this will land in Protostar v0.4

**Comment by JorikSchellekens** [comment]
Amazing! Thank you @mkaput
