### ISSUE TITLE
Port Protostar state cheats to Cairo 0.10 new classes

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#700]
We don't have to maintain 2 forkable states. Protostar state should be possibly independent of cairo-lang.

**Comment by MaksymilianDemitraszek** [comment]
How do you plan to supply the state to `protostar/starknet/cheatable_syscall_handler.py`?

**Comment by kasperski95** [comment]
Similarly to `cheatcode_factory`.

**Comment by MaksymilianDemitraszek** [comment]
Not sure what you mean tbh, could you please elaborate?
