### ISSUE TITLE
Think of a simpler example when describing setup cases

### ISSUE THREAD

**Issue by mkaput** [software-mansion/protostar#726]
Yea, deploy contract is a bit weird. I just have a feeling that `max_examples` is not a simple enough cheatcode for an example, as you have to know what fuzzing is beforehand which makes learning curve steeper. 

Alternative idea, which _maybe_ tells a better story
```
    func __setup__():
        deploy_contract()
    end

     func setup_test_a():
        store(5)
    end

     func test_a():
        assert load() = 5
    end

     func test_b():
        assert load() = 0
    end
```

leaving the decision to you

_Originally posted by @MaksymilianDemitraszek in https://github.com/software-mansion/protostar/pull/703#discussion_r960489050_

**Comment by mkaput** [comment]
I thought about this a little and my conclusions are:
1. The store&load example is not good, because you can simply put the overriding store call inside `test_a` directly.
2. Current docs state `Use case hooks to configure the behavior of particular test case,
for example, by calling the max_examples cheatcode.`. This is actually quite correct statement describing what is this used for, and the provided example supplements it.

I don't see other feasible usage cases using current feature set. I think we should leave this as -is.

**Comment by MaksymilianDemitraszek** [comment]
> The store&load example is not good, because you can simply put the overriding store call inside test_a directly.

Yes you can, but I believe this feature (hooks per case) has been requested many times after we introduced setup hooks.  I think users like the logical separation between setup, and case as it improves readability.

IMO current docs are lacking in explanation how actually `setup_case` hooks work introducing them only as a space to configure strategies, even though there are more usecases.

I am not sure about the change though. Feel free to close the issue if arguments above aren't sufficient.
