### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by Solpatium** [software-mansion/protostar#750]
As a StarkNet smart contract developer, I want to be able to use protostar on [Windows](https://szl.wikipedia.org/wiki/Microsoft_Windows) so that I can get the best StarkNet experience.

It is possible to use protostar through WSL, but this does not create a great user experience. This is especially a problem when doing some workshops.

**Comment by Solpatium** [comment]
We should at least describe how to install it using WSL.

**Comment by MaksymilianDemitraszek** [comment]
I don't think we are planning to support Windows in the near future, closing
