### ISSUE TITLE
Require git only when it is needed 

### ISSUE THREAD

**Issue by Solpatium** [software-mansion/protostar#751]
As a StarkNet smart contract developer, I want to use `protostar test` command without updating my git. Maybe it is possible to require git only for commands the use it?

This makes installation easier and saves time. It would be especially useful on workshops.

**Comment by mkaput** [comment]
Essentially this task boils do to importing `GitPython` lazily only inside functions that use it, instead of importing it in modules directly.

**Comment by mkaput** [comment]
Another option: https://www.dulwich.io/

**Comment by Radinyn** [comment]
#850
