### ISSUE TITLE
Allow skipping tests

### ISSUE THREAD

**Issue by mkaput** [software-mansion/protostar#765]
As a StarkNet smart contract developer, I want to leave a `skip` annotation in test suite source code so that the test case is not executed with a description message saying why is the test skipped.

Proposed semantics using setup cases and a new cheatcode:

```cairo
func __setup__() {
    %{ print("Setup hook is executed.") %}
    // but you can call skip here to skip *entire* test suite.
    return ()
}

func setup_skipped() {
    %{ skip(reason="Message.") %}
    // or skipif:
    %{ skip(condition=..., reason="Message.") %}
}

func test_skipped() {
    %{ assert False, "This should not be executed." %}
    return ()
}
```

Ref: https://docs.pytest.org/en/7.1.x/how-to/skipping.html

**Comment by kasperski95** [comment]
Currently, a user can use `--ignore` flag to achieve similar functionality:

`test_foo__skip_message`
`protostar test ./tests --ignore ::*__skip*`

**Comment by mkaput** [comment]
I think both features can complement each other. Skipping can be used for more persisted usage when something is in progress etc. Like we do in Protostar ;)
