### ISSUE TITLE
Protostar Init prompts to have access to Photos, Desktop, etc. in terminal 

### ISSUE THREAD

**Issue by rlkelly** [software-mansion/protostar#782]
## Protostar version

0.3.2

| Name       | Version              |
| ---------- | -------------------- |
Protostar version: 0.3.2
Cairo-lang version: ^0.9.1
15:35:14 [INFO] Execution time: 0.98 s
| Git        | ` 2.37.2`        |

## Current Behavior
It prompts to access my downloads and photos

## Expected Behavior
I shouldn't be prompted by this alert

## Steps to Reproduce
1. Install protostar on a new machine
2. run "protostar init"

## Possible Solution
This may be an issue with an underlying library

**Comment by mkaput** [comment]
What machine are you referring to? macOS? What version?

In what directory are you calling Protostar? We are searching for any Cairo files in all subdirectories of current working directory, so if you are running Protostar in your home directory `~`, then yes, it will try to access Photos, Desktop etc.

**Comment by rlkelly** [comment]
yep, that's probably it.  Thanks for clarifying!
