### ISSUE TITLE
RFC: Decouple Protostar from StarkNet

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#783]
Protostar is heavily coupled with StarkNet which:
- increases maintenance and modification cost 
- delays releases relatively to `cairo-lang`
- makes the boundary between Protostar and StarkNet vague
 
This proposal suggest:
- introducing an abstract module (protostar.blockchain) between Protostar and StarkNet
  - StarkNet internals are unstable, hence shouldn't be used as a dependency
    > The dependencies between packages should be in the direction of the stability of the packages. A package should only depend upon packages that are more stable than it is.
https://wiki.c2.com/?StableDependenciesPrinciple
    - [Fundamental theorem of software engineering](https://en.wikipedia.org/wiki/Fundamental_theorem_of_software_engineering)
  - Abstraction represents Protostar's expectations from StarkNet, which could allow us to move some parts of the adapter to the `cairo-lang` package reducing the maintenance cost
  - better modularity improves work separation / code ownership
  - improved testability removes the need for creating integration tests when it's not necessary resulting in faster tests
  - recreating Protostar and StarkNet in Rust is going to be easier if both teams know interface ahead
- keeping Protostar state in the `TestExecutionState` rather than in the adapter module
  - currently, part of the state is kept in the `TestExecuteState`  (e.g. `TestContext`) and other part in `CheatableState` for unknown reasons

![Image](https://user-images.githubusercontent.com/9629577/189210128-c3296224-f567-46b0-b315-725bab8c31e9.png)

**Comment by kasperski95** [comment]
`TestExecutionStateSelector` is a bad idea. Instead, `CheatableBlockchainCommander` should allow adding middleware functions.

**Comment by mkaput** [comment]
The `CheatableBlockchainCommander` seems to fulfil exactly the same role as `Cheaters` which I pursue in #775. I think we just thought of different names

**Comment by kasperski95** [comment]
I'd say `Commander` it's a higher abstraction.

`BlockInfoCheater` leaks `StarkNet` implementation details in its name.

**Comment by mkaput** [comment]
Yeah, that's right

**Comment by kasperski95** [comment]
The problem I see with `Cheaters` is that they manage the state of the cheat, and the `Cheaters` are part of the adapter (`protostar.starknet`).

Ideally, the adapter should be moved to `cairo-lang` package, hence the state must be kept on the Protostar side.

```python
def cheatcode_listener(cheatcode_name: str, context, *args, **kwargs):
    if cheatcode_name == "warp":
        state.warp[context.contract_address] = args[0]

def modify_block_timestamp(contract_address, block_timestamp):
    if contract_address in state.warp:
        return state.warp[contract_address]
    return block_timestamp

blockchain.subscribe_to_cheatcode_calls(cheatcode_listener)
blockchain.add_cheatcode("warp")
blockchain.register_block_timestamp_interceptor(modify_block_timestamp)

```

**Comment by mkaput** [comment]
> Ideally, the adapter should be moved to `cairo-lang` package, hence the state must be kept on the Protostar side.

The trick is that we 99% will not get this anytime, given Starkware is focused on migrating to Rust

**Comment by mkaput** [comment]
> The problem I see with `Cheaters` is that they manage the state of the cheat, and the `Cheaters` are part of the adapter (`protostar.starknet`).
> 
> Ideally, the adapter should be moved to `cairo-lang` package, hence the state must be kept on the Protostar side.
> 
> ```python
> def cheatcode_calls_listener(cheatcode_name: str, context, *args, **kwargs):
>     if cheatcode_name == "warp":
>         state.warp[context.contract_address] = args[0]
> 
> def modify_block_timestamp(contract_address, block_timestamp):
>     if contract_address in state.warp:
>         return state.warp[contract_address]
>     return block_timestamp
> 
> blockchain.add_cheatcode("warp")
> blockchain.subscribe_to_cheatcode_calls(cheatcode_listener)
> blockchain.register_block_timestamp_interceptor(modify_block_timestamp)
> ```

I think the current API of Cheatcodes as classes is much more lean than this; and they accept a proxy object to Blockchain as a single constructor argument. Welp, we could even simplify that with following pattern which would work for all cheatcodes we have:

```python
def build_warp_cheatcode(cheaters: Cheaters):
    def warp(arg, arg, arg, ...):
        do the cheats

    return warp
```

**Comment by kasperski95** [comment]
```py 
blockchain.add_cheatcode(WarpCheatcode(blockchain, state))
```

```py
class WarpCheatcode(Cheatcode):
    def __init__(self, blockchain, state):
        self._blockchain = blockchain,
        self._state=state

    @property
    def name(self) -> str:
        return "warp"

    def on_mount(self) -> Optional[UnmountCallback]:
        return self._blockchain.register_block_timestamp_interceptor(self._modify_block_timestamp)

    def _modify_block_timestamp(self, contract_address, block_timestamp):
        if contract_address in self.state.warp:
            return self.state.warp[contract_address]
        return block_timestamp

    def run(self, context, *args, **kwargs) -> Any:
        return self.warp(context.contract_address, *args, **kwargs)

    def _warp(
        self,
        current_contract_address: int,
        blk_timestamp: int,
        target_contract_address: Optional[int] = None,
    ) -> Callable:
        self.state.warp[target_contract_address or current_contract_address] = blk_timestamp

        def cancel_warp():
            del self.state.warp[target_contract_address or current_contract_address]

        return cancel_warp
```

**Comment by mkaput** [comment]
> ```python
> blockchain.add_cheatcode(WarpCheatcode(blockchain, state))
> ```
> 
> ```python
> class WarpCheatcode(Cheatcode):
>     def __init__(self, blockchain, state):
>         self._blockchain = blockchain,
>         self._state=state
> 
>     @property
>     def name(self) -> str:
>         return "warp"
> 
>     def on_mount(self) -> Optional[UnmountCallback]:
>         return self._blockchain.register_block_timestamp_interceptor(self._modify_block_timestamp)
> 
>     def _modify_block_timestamp(self, contract_address, block_timestamp):
>         if contract_address in self.state.warp:
>             return self.state.warp[contract_address]
>         return block_timestamp
> 
>     def run(self, context, *args, **kwargs) -> Any:
>         return self.warp(context.contract_address, *args, **kwargs)
> 
>     def _warp(
>         self,
>         current_contract_address: int,
>         blk_timestamp: int,
>         target_contract_address: Optional[int] = None,
>     ) -> Callable:
>         self.state.warp[target_contract_address or current_contract_address] = blk_timestamp
> 
>         def cancel_warp():
>             del self.state.warp[target_contract_address or current_contract_address]
> 
>         return cancel_warp
> ```

1. I think `on_mount` could be simply done within `__init__` here, wdyt?
3. Passing extra magic `context` parameter will make parameter mismatch (wrong count, bad kwarg name) exceptions less informative. And cheatcode parameter `context` will be illegal.
4. I think `context` could be reffered via `self.context` which is a `@final` property implemented in `Cheatcode` which gets its value by asking `self.blockchain`
5. The `state` field leaks too much information. It is tempting to make it a god object which is also blockchain-impl specific. Cheaters solve that by encapsulating smaller chunks of state manipulation.

**Comment by kasperski95** [comment]
> 1. I think on_mount could be simply done within __init__ here, wdyt?

Constructors shouldn't create side effects if possible. Interceptor registration should happen after calling `add_cheatcode`.

> 2. Passing extra magic context parameter will make parameter mismatch (wrong count, bad kwarg name) exceptions less informative. And cheatcode parameter context will be illegal.

```python
def build(self, context: ExecutionContext) -> Any:
    def warp(blk_timestamp: int, target_contract_address: Optional[int] = None):
        self.state.warp[target_contract_address or context.contract_address] = blk_timestamp
        def cancel_warp():
            del self.state.warp[target_contract_address or context.contract_address]
        return cancel_warp
    return warp
```


> 3. I think context could be reffered via self.context which is a @final property implemented in Cheatcode which gets its value by asking self.blockchain

- `self._blockchain.context` — it doesn't make sense
- `self._blockchain.active_execution_context` — what if the blockchain supports runs execution concurrently?
- `self._blockchain.execution_contexts[0]` — the blockchain would have to manage the state of execution contexts

Retrieving context from `self._blockchain` looks weird to me. Usually, contexts are passed as parameters.

- https://api.flutter.dev/flutter/widgets/StatelessWidget/build.html
- https://docs.nestjs.com/guards

>  It is tempting to make it a god object which is also blockchain-impl specific. 

The state uses quite generic terms.
```py
self.pranked_contracts_map: Dict[int, int] = {}
self.mocked_calls_map: Dict[AddressType, Dict[SelectorType, List[int]]] = {}
self.event_selector_to_name_map: Dict[int, str] = {}
self.event_name_to_contract_abi_map: Dict[str, AbiType] = {}
self.class_hash_to_contract_abi_map: Dict[ClassHashType, AbiType] = {}
self.class_hash_to_contract_path_map: Dict[ClassHashType, Path] = {}
self.contract_address_to_class_hash_map: Dict[AddressType, ClassHashType] = {}
self.contract_address_to_block_timestamp: dict[AddressType, int] = {}
self.contract_address_to_block_number: dict[AddressType, int] = {}
```


> The state field leaks too much information. 

```py
class WarpCheatcodeState(Protocol):
    def get_cheated_block_timestamp(self, contract_address: int) -> Optional[int]:
        ...

    def set_cheated_block_timestamp(self, block_timestamp: Optional[int]) -> None:
        ...

class WarpCheatcode(Cheatcode):
    def __init__(self, blockchain, state: WarpCheatcodeState):
        self._blockchain = blockchain,
        self._state=state

    @property
    def name(self) -> str:
        return "warp"

    def on_mount(self) -> Optional[UnmountCallback]:
        return self._blockchain.register_block_timestamp_interceptor(self._modify_block_timestamp)

    def _modify_block_timestamp(self, contract_address, block_timestamp):
        return self._state.get_cheated_block_timestamp(contract_address) or block_timestamp

def build(self, context: ExecutionContext) -> Any:
    def warp(blk_timestamp: int, target_contract_address: Optional[int] = None):
        self._state.set_cheated_block_timestamp(target_contract_address or context.contract_address, blk_timestamp)
        def cancel_warp():
            self._state.set_cheated_block_timestamp(target_contract_address or context.contract_address, None)
        return cancel_warp
    return warp
```

> Cheaters solve that by encapsulating smaller chunks of state manipulation.

Cheaters are on the wrong side of the boundary. They will prevent moving the adapter part to the `cairo-lang` library.

**Comment by kasperski95** [comment]
> The name is bad, but in general I don't see why they couldn't be put into cairo-lang.

Because it doesn't have to be in that package. Changes to `cairo-lang` should be minimal. The state is used by Protostar cheatcodes and they are on the Protostar side e.g.:
- `pranked_contracts_map` - `start_prank`
- `mocked_calls_map` - `mock_call`
- `class_hash_to_contract_path_map` - `declare`, `deploy_contract`

> Hmm, and what about returning a list of interceptors declaratively? Instead of imperatively registering and deregistering these.

Can you provide an example?

> And that's the problem. It takes care of too many things.

The state keeps cheatcode's state. Cheatcodes are on the Protostar side, so it should be state. The state can be implemented similarly to cheaters or through protocols.

> WarpCheatcodeState looks like a cheater. 1:1

Cheaters are StarkNet specific (BlockInfo, copy, apply). CheatcodeState should be blockchain independent (fork method should be enough).

**Comment by mkaput** [comment]
We have to discuss this F2F soon.

**Comment by MaksymilianDemitraszek** [comment]
Closing in favour of #987
