### ISSUE TITLE
Update Starknet.py to v0.6.0a0

### ISSUE THREAD

**Issue by mkaput** [software-mansion/protostar#835]

**Comment by Bal7hazar** [comment]
Hey, I have an issue when I try to invoke a deployed contract with the `starknet` CLI (installed with starnet.py 0.6.0) while I use abi generated from protostar 0.4.2.

Do you think it comes from the fact than `protostar`  still use 0.5.x starknet.py version ?

Note: the same command line with the same abi file works fine using protostar 0.4.2 and starknet 0.5.x.

**Comment by mkaput** [comment]
> Hey, I have an issue when I try to invoke a deployed contract with the `starknet` CLI (installed with starnet.py 0.6.0) while I use abi generated from protostar 0.4.2.
> 
> Do you think it comes from the fact than `protostar` still use 0.5.x starknet.py version ?
> 
> Note: the same command line with the same abi file works fine using protostar 0.4.2 and starknet 0.5.x.

Hey @Bal7hazar !

You haven't described what error you get, but this seems more related to #834 which surfaced a problem with Starknet tx versions we got. The PR for that issue may help you.

**Comment by Bal7hazar** [comment]
> You haven't described what error you get,

My apologizes :sweat:

My issue is that I get the following error : `StarknetErrorCode.ENTRY_POINT_NOT_FOUND_IN_CONTRACT` when I try to invoke an external of my contract with the abi file generated from protostar 0.4.2 and using starknet from cairo-lang 0.10.

It works well when with both of the following setup:
- abi generated with protostar 0.4.2 and starknet from cairo-lang 0.9.1
- abi generated with protostar 0.3.x and starknet from cairo-lang 0.9.1

In my understanding I think the latest 0.4.2 version generate a abi which is not compatible with the latest starknet CLI.
I hope this is clear enough.

**Comment by mkaput** [comment]
OK, I think you get exactly the thing I discovered on Friday (error code and circumstances check) 😅 #834 fixes it.

Protostar was always using Starknet transaction version 0 until the fix (a bug!), while your Account is using v1. It's not strictly related to the ABI of your contract.
