### ISSUE TITLE
Unexpected Protostar error, expected exactly 1 expressions, got 5.

### ISSUE THREAD

**Issue by iamreadyi** [software-mansion/protostar#885]
## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `0.4.2`  |
| Cairo-lang | `0.10.0` |

Unexpected Protostar error. Report it here:
https://github.com/software-mansion/protostar/issues

test_staking_rewards.cairo:90:5: Expected exactly 1 expressions, got 5.
    IStaking.add_token_pair(staking_contract_address, 15, staking_token_address, 30, reward_token_address);
    ^****************************************************************************************************^

I remember it was working previously. Interface and contract is right.

**Comment by kasperski95** [comment]
Can't reproduce. Can you share a link to your repo?

**Comment by iamreadyi** [comment]
> Can't reproduce. Can you share a link to your repo?

test => https://github.com/iamreadyi/cairo-synthetic-staking-and-lottery/blob/main/tests/test_staking_rewards.cairo#L76

relevant function => https://github.com/iamreadyi/cairo-synthetic-staking-and-lottery/blob/main/src/staking_rewards.cairo#L283

**Comment by Radinyn** [comment]
Current:
```
    func add_token_pair() -> (
        for_stake_token_name: felt,
        for_stake_token_address: felt,
        for_reward_token_name: felt,
        for_reward_token_address: felt,
    ) {
    }```

New:
```
    func add_token_pair(
        for_stake_token_name: felt,
        for_stake_token_address: felt,
        for_reward_token_name: felt,
        for_reward_token_address: felt
        ) {
    }
```


I think you might have confused the input with the return values here. Currently the function only expects the contract address as a parameter.

**Comment by iamreadyi** [comment]
Thanks man. I need to take some break.

**Comment by iamreadyi** [comment]
> Current:
> 
> ```
>     func add_token_pair() -> (
>         for_stake_token_name: felt,
>         for_stake_token_address: felt,
>         for_reward_token_name: felt,
>         for_reward_token_address: felt,
>     ) {
>     }
> ```
> 
> New:
> 
> ```
>     func add_token_pair(
>         for_stake_token_name: felt,
>         for_stake_token_address: felt,
>         for_reward_token_name: felt,
>         for_reward_token_address: felt
>         ) {
>     }
> ```
> 
> I think you might have confused the input with the return values here. Currently the function only expects the contract address as a parameter.

thanks... i need some break.
