### ISSUE TITLE
Add a shorter name of `protostar` to PATH to make typing easier

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#894]
As a Protostar user, I want to type a shorter version of `protostar` word, to avoid typing the fullname for every interaction with Protostar.

T.B.D.
- `protostar test`
- `proto test`
- `ptsr test`
- `psr test`

**Comment by Arcticae** [comment]
idk if that's a valid issue, if anyone wants a shorter version, they can just alias it

**Comment by kasperski95** [comment]
Ok, let's stick with the full name. Providing two entry points could be confusing.
