### ISSUE TITLE
Validate input provided to `deploy` cheatcode and show user-friendly error message

### ISSUE THREAD

**Issue by iamreadyi** [software-mansion/protostar#912]
I try to deploy 2 token contracts and a contract that uses tokens but i get this error.

test function : https://github.com/iamreadyi/synthetic_staking_lottery_cairo/blob/main/tests/test_staking.cairo#L26

repo : 
https://github.com/iamreadyi/synthetic_staking_lottery_cairo

error : protostar test
14:10:19 [INFO] Collected 1 suite, and 1 test case (0.159 s)                                             
[FAIL] tests/test_staking.cairo test_staking_contract (time=9.59s)                                       
[type] TRANSACTION_FAILED
[code] 43
[details]:
tests/test_staking.cairo:34:5: Error at pc=0:79:
Got an exception while executing a hint.
    %{ ids.staking_token_address = deploy_contract("./src/staking_token.cairo").contract_address %} 
    ^*********************************************************************************************^
Cairo traceback (most recent call last):
tests/test_staking.cairo:26:6: (pc=0:110)
func test_staking_contract{syscall_ptr: felt*, range_check_ptr, pedersen_ptr: HashBuiltin*}() {
     ^*******************^

Error in the called contract (0x4b4bc243d1405b953caa458bff8fb9adac456a63def323dc71d585e4d3751ad):
Error at pc=0:1220:
An ASSERT_EQ instruction failed: 10:1 != 10:0.

                                                                                                         
14:10:32 [INFO] Test suites: 1 failed, 1 total                                                           
14:10:32 [INFO] Tests:       1 failed, 1 total
14:10:32 [INFO] Seed:        1552878466
14:10:32 [INFO] Execution time: 14.26 s

**Comment by kasperski95** [comment]
`staking_token` expects `owner` argument
