### ISSUE TITLE
Allow mocking calls to not deployed contracts

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#944]
https://discord.com/channels/793094838509764618/1027254917234163753

**Comment by Arcticae** [comment]
`mock_call` docs should be updated (in scope of this issue)

**Comment by MarekHauzr** [comment]
Hi, we have a similar problem...
in module foo.cairo
```
const ADDRESS = 0x0446812bac98c08190dee8967180f4e3cdcd1db9373ca269904acb17f67f7093;
```
in test test_something.cairo
```
from ... import KEY

@external
func test_func_that_has_get_value_inside{range_check_ptr, syscall_ptr: felt*}() {
    %{
        stop_mock = mock_call(
            ids.ADDRESS, "get_value", [1480230000000000000000, 18, 0, 0]
        )
    %}
    let (res) = func_that_has_get_value_inside(KEY);
    %{ stop_mock() %}
    assert res = 3413177997528386198568;
    return ();
}
```
when we hint-print inside test_func_that_has_get_value_inside, it shows correct ADDRESS... but fails with  `Requested contract address ... is not deployed.`

Fun thing is that when we do
```
@external
func test_empiric_median_price{range_check_ptr, syscall_ptr: felt*}() {
    **let boo = EMPIRIC_ORACLE_ADDRESS**;
    %{
        stop_mock = mock_call(
            **ids.boo**, "get_value", [1480230000000000000000, 18, 0, 0]
        )
    %}
    let (res) = empiric_median_price(EMPIRIC_ETH_USD_KEY);
    %{ stop_mock() %}
    assert res = 3413177997528386198568;
    return ();
}
```
it works...

another fun thing is that the above fails only for 0x0446812bac98c08190dee8967180f4e3cdcd1db9373ca269904acb17f67f7093 (empiric oracle), but works for older empiric contract 0x012fadd18ec1a23a160cc46981400160fbf4a7a5eed156c4669e39807265bcd4 and even for random things like 0x123456789

**Comment by karol-bisztyga** [comment]
Hey!

I took a look at this and it looks like in cairo `const`s don't work in hints.

In the [docs](https://www.cairo-lang.org/docs/how_cairo_works/consts.html?highlight=const#consts) we can read:
> The line `const value = 1234` is not translated to a Cairo instruction; it is just used by the compiler to replace `value` with `1234` in the following instructions.

Please, take a look at this:

```

const CNST = 0x4d599dd218f30de54f77b48eeeff0321b1c65db2f185c36c88c79bd1f5879742;

@external
func test_consts{
    syscall_ptr: felt*, range_check_ptr, pedersen_ptr: HashBuiltin*, ecdsa_ptr: SignatureBuiltin*
}() {
    let n = 0x4d599dd218f30de54f77b48eeeff0321b1c65db2f185c36c88c79bd1f5879742;
    assert n = CNST; // pass
    %{
        assert ids.CNST == ids.n # fail
    %}
    return ();
}
```

For some reason, this works if we operate on small values, but I'm not really sure if it's worth investigating. You can just reassign the constant to a local variable as @MarekHauzr suggested.

Mocking calls to contracts that are not deployed works:

```

@contract_interface
namespace MainContract {
  func do_something() -> (res: felt) {
  }
}

const CONST_ADDR = 0x4d599dd218f30de54f77b48eeeff0321b1c65db2f185c36c88c79bd1f5879742;

@external
func test_something{
    syscall_ptr: felt*, range_check_ptr, pedersen_ptr: HashBuiltin*, ecdsa_ptr: SignatureBuiltin*
}() {
    tempvar fake_addr = CONST_ADDR;
    %{
        stop_mock = mock_call(ids.fake_addr, "do_something", [999])
    %}
    let (res) = MainContract.do_something(fake_addr);
    %{
        assert ids.res == 999
        stop_mock()
    %}
    return ();
}
```

I'm considering this as resolved, if you feel like it's not, please let me know, we can reopen and discuss this further.

Cheers.

**Comment by MarekHauzr** [comment]
@karol-bisztyga thanks for the answer... I think we can close this since this is cairo problem and not protostar problem... 

@Chepelau, @tensojka have a look at the answer, it' interesting
