### ISSUE TITLE
Rethink migrations

### ISSUE THREAD

**Issue by mkaput** [software-mansion/protostar#970]
We are starting to think that the current form of migrations is not super nice to use.

The goal is to seed a research for a new migrations/deployment scripts design that will be more elegant and ergonomic.

**Comment by kasperski95** [comment]
### Standard flow:
`protostar install && protostar test && protostar build && protostar -p e2e test && protostar migrate`

### Something went wrong on production:
`protostar migrate --rollback`

---

`protostar migrate` should copy files from `protostar build`'s output to migration specific directory. Contract names should be resolved to contracts in that specific directory, not in the build output.

Protostar needs to track somehow what is deployed and what is not.

**Comment by mkaput** [comment]
Related issues:
- https://github.com/software-mansion/protostar/issues/518
- https://github.com/software-mansion/protostar/issues/954
